packages/client/package.json, packages/client/src/App.tsx, packages/client/src/main.tsx, packages/components/src/components/Alert/index.scss, packages/components/src/components/Alert/package-relation.tsx, packages/components/src/components/Badge/index.tsx, packages/components/src/constants.tsx
=> optimize(client):overall page UI optimize

.changeset/pre.json
- feat(client): add module anaysis components
- feat(platform): report platform add bundle size page
- feat(client): add timeline chart & loader analysis page
- feat(client): Overall Page‘s compile overall card add details timeline
- feat(client): add resolve & loader & plugin pages
- feat: migrate rsdoctor packages
- fix(graph): duplicate pkg version
- fix(components): some components types.
- Rsdoctor report platform add overall page (close: #25)
- refactor(client): migrate build tool to Rsbuild
=> Release v0.0.2-beta.1

packages/components/src/components/Card/index.tsx, packages/components/src/components/FileTree/index.tsx, packages/components/src/components/Loader/Analysis/files.tsx, packages/components/src/components/Loader/executions.tsx, packages/components/src/utils/monaco.ts
1. Pre-acquire monaco static resources to solve the problem of code display stuttering.
2. Optimize Loader Analysis UI, add folding loader environmental parameter capability.
=> feat(client): Pre-acquire monaco static resources

packages/components/src/components/Card/statistic.scss, packages/components/src/components/Layout/index.tsx, packages/components/src/components/Overall/bundle.tsx, packages/components/src/constants.tsx, packages/components/src/pages/BundleSize/components/asset.tsx, packages/components/src/pages/BundleSize/components/cards.tsx, packages/components/src/pages/BundleSize/components/index.scss, packages/components/src/pages/BundleSize/components/index.tsx
=> [WIP]Fix/optimize UI bundle page

README.md, README.zh-CN.md
Update Rsdoctor banner image.
https://github.com/web-infra-dev/rsdoctor/assets/7237365/0f9d2e86-d919-451a-befa-fa84603a87cf
=> docs: update Rsdoctor banner image

packages/client/src/router.tsx, packages/components/package.json, packages/components/src/components/Charts/TimelineCharts/index.tsx, packages/components/src/components/Charts/loader.tsx, packages/components/src/pages/BundleSize/components/cards.tsx, packages/components/src/pages/Resources/RuleIndex/constants.ts, packages/components/src/pages/Resources/RuleIndex/index.tsx, packages/components/src/pages/index.ts, pnpm-lock.yaml
Optimize(client): optimize some ui
=> Optimize(client): optimize some ui

document/docs/en/guide/start/intro.mdx, document/docs/zh/guide/start/intro.mdx
chore(docs): rsdoctor introduction document
#14
#15
=> chore(docs): rsdoctor introduction document

document/docs/en/_meta.json, document/docs/en/guide/start/_meta.json, document/docs/en/guide/start/quick-start.mdx, document/docs/en/index.md, document/docs/zh/_meta.json, document/docs/zh/guide/start/_meta.json, document/docs/zh/guide/start/quick-start.mdx, document/docs/zh/index.md, document/package.json, document/rspress.config.ts, document/theme/components/HomeFeatures/index.module.scss, document/theme/components/HomeFeatures/index.tsx, document/theme/components/HomeFooter/index.tsx, document/theme/components/HomeHero/index.module.scss, document/theme/components/HomeHero/index.tsx, document/theme/index.css, document/theme/index.tsx, document/theme/pages/index.tsx, document/theme/types.d.ts, document/tsconfig.json, examples/rspack-minimal/package.json, examples/rspack-minimal/rspack.config.js, pnpm-lock.yaml
chore(docs): rsdoctor docs fix some problem
=> chore(docs): rsdoctor docs fix some problem

packages/components/src/components/TextDrawer/duplicate.tsx
fix(client): rspack projects Overall page error 
#98
=> fix(client): rspack projects Overall page error #98

packages/graph/src/graph/package-graph/graph.ts
fix(graph): duplicate packages error
=> fix(graph): duplicate packages error

document/docs/en/guide/start/quick-start.mdx, document/docs/zh/guide/start/quick-start.mdx
chore(docs): optimize quick start document
=> chore(docs): optimize quick start document

document/docs/en/guide/usage/_meta.json, document/docs/en/guide/usage/compile-overall.mdx, document/docs/zh/guide/usage/_meta.json, document/docs/zh/guide/usage/compile-overall.mdx, document/theme/index.css, examples/rsbuild-minimal/rsbuild.config.ts
chore(docs): usage's compile overall documentation
#14 
#15
=> chore(docs): usage's compile overall documentation

document/docs/en/guide/start/features.mdx, document/docs/en/guide/usage/_meta.json, document/docs/en/guide/usage/resolver.mdx, document/docs/zh/guide/start/features.mdx, document/docs/zh/guide/usage/_meta.json, document/docs/zh/guide/usage/bundle-overall.mdx, document/docs/zh/guide/usage/compile-overall.mdx, document/docs/zh/guide/usage/project-overall.mdx, document/docs/zh/guide/usage/resolver.mdx, packages/components/src/components/Charts/common.tsx, packages/components/src/utils/storage.tsx
chore(docs): add resolver-analysis documents
#14 
#15
=> chore(docs): add resolver-analysis documents

document/docs/en/guide/start/features.mdx, document/docs/en/guide/usage/_meta.json, document/docs/en/guide/usage/compile-overall.mdx, document/docs/en/guide/usage/loaders-timeline.mdx, document/docs/zh/guide/start/features.mdx, document/docs/zh/guide/usage/_meta.json, document/docs/zh/guide/usage/loaders-timeline.mdx, packages/components/src/pages/WebpackLoaders/Overall/constants.ts, packages/components/src/pages/WebpackLoaders/Overall/index.tsx, packages/components/src/utils/i18n/cn.ts, packages/components/src/utils/i18n/en.ts
chore(docs): add loaders analysis documentation
#14
=> chore(docs): add loaders analysis documentation

packages/components/src/components/Configuration/builder.tsx, packages/components/src/components/Configuration/index.tsx, packages/components/src/utils/hooks.ts, packages/rspack-plugin/src/plugin.ts, packages/types/src/plugin/baseStats.ts, packages/types/src/sdk/config.ts
fix(plugin): rspack mode builder config report error
=> fix(plugin): rspack mode builder config report error

document/docs/en/guide/_meta.json, document/docs/en/guide/start/features.mdx, document/docs/en/guide/topic/_meta.json, document/docs/en/guide/topic/loader-optimization.mdx, document/docs/zh/guide/_meta.json, document/docs/zh/guide/start/features.mdx, document/docs/zh/guide/topic/_meta.json, document/docs/zh/guide/topic/loader-optimization.mdx
chore(docs): add loader optimize documentation
#14
=> chore(docs): add loader optimize documentation

document/docs/zh/guide/topic/_meta.json, document/docs/zh/guide/topic/duplicate-pkg-problem.mdx
=> docs: add duplicate-pkg-problem topic documention

document/docs/en/guide/start/features.mdx, document/docs/en/guide/topic/_meta.json, document/docs/en/guide/topic/duplicate-pkg-problem.mdx, document/docs/zh/guide/start/features.mdx, document/docs/zh/guide/topic/duplicate-pkg-problem.mdx
chore(docs): add duplicate packages analysis documents
#14
=> chore(docs): add duplicate packages analysis documents

document/docs/en/guide/start/features.mdx, document/docs/en/guide/start/intro.mdx, document/docs/en/guide/usage/_meta.json, document/docs/en/guide/usage/bundle-alerts.mdx, document/docs/en/guide/usage/bundle-overall.mdx, document/docs/en/guide/usage/bundle-size.mdx, document/docs/en/guide/usage/compile-overall.mdx, document/docs/en/guide/usage/loaders-analysis.mdx, document/docs/en/guide/usage/module-analysis.mdx, document/docs/zh/guide/start/features.mdx, document/docs/zh/guide/usage/_meta.json, document/docs/zh/guide/usage/bundle-alerts.mdx, document/docs/zh/guide/usage/bundle-overall.mdx, document/docs/zh/guide/usage/compile-overall.mdx, document/docs/zh/guide/usage/loaders-analysis.mdx, document/docs/zh/guide/usage/module-analysis.mdx
chore(docs): add modules analysis documents
#14
=> chore(docs): add modules analysis documents

packages/rspack-plugin/src/plugin.ts
fix(plugin): tile graph generate error
=> fix(plugin): tile graph generate error

.changeset/ninety-snakes-own.md
chore: release 0.1.0 changeset
=> chore: release 0.1.0 changeset

README.md, README.zh-CN.md
=> chore: optimize readme

document/docs/en/guide/start/quick-start.mdx, document/docs/zh/guide/start/quick-start.mdx
Use PackageManagerTabs for installing:
- before
- after
https://rspress.dev/api/client-api/api-components.html#packagemanagertabs
=> docs: use PackageManagerTabs for installing

.github/workflows/lint.yml, .github/workflows/test-ubuntu.yml, .github/workflows/test-windows.yml, CONTRIBUTING.md, package.json, scripts/skipCI.js, scripts/update-packages/src/rspress.ts
Update document path, the website has been moved to `/root/document`.
=> chore(workflow): update document path

.vscode/extensions.json, .vscode/settings.json, CONTRIBUTING.md, biome.json, document/theme/components/HomeFeatures/index.tsx, examples/modern-minimal/src/routes/page.tsx, package.json, packages/components/src/components/Charts/utils.ts, packages/components/src/utils/loader.ts, packages/components/src/utils/request.ts, packages/core/src/build-utils/build/utils/loader.ts, packages/core/src/build-utils/build/utils/parseBundle.ts, packages/core/src/build-utils/common/chunks/assetsModules.ts, packages/core/src/build-utils/common/webpack/compatible.ts, packages/core/src/inner-plugins/plugins/loader.ts, packages/core/src/inner-plugins/utils/loader.ts, packages/rspack-plugin/src/builtinLoaderPlugin.ts, packages/test-helper/src/index.ts, packages/types/src/emo.ts, packages/types/src/error.ts, packages/types/src/thirdparty.ts, packages/utils/src/common/loader.ts, packages/utils/src/rule-utils/parser/types.ts, packages/webpack-plugin/src/multiple.ts, packages/webpack-plugin/src/plugin.ts, packages/webpack-plugin/src/plugins/resolver.ts, pnpm-lock.yaml, scripts/check-changeset/src/index.ts, scripts/modern.base.config.ts, scripts/skipCI.js
fix: add biome as lint tool and fix some lint error
=> fix: add biome as lint tool and fix some lint error

document/docs/en/blog/release/release-note-1.mdx, document/docs/en/guide/start/intro.mdx, document/docs/en/guide/start/quick-start.mdx, document/docs/zh/blog/release/release-note-1.mdx, document/docs/zh/guide/start/intro.mdx, document/docs/zh/guide/start/quick-start.mdx
chore(docs): optimize start docs
#14
=> chore(docs): optimize start docs

document/docs/en/blog/release/release-note-1.mdx, document/docs/zh/blog/release/release-note-1.mdx
chore(docs): optimize release note
=> chore(docs): optimize release note

.changeset/six-mice-rhyme.md, packages/core/src/inner-plugins/plugins/bundle.ts, packages/core/src/inner-plugins/plugins/summary.ts, packages/core/src/types/plugin.ts, packages/rspack-plugin/src/plugin.ts
fix(plugin): plugin types error.
=> fix(plugin): plugin types error.

packages/components/src/components/Alert/package-relation.tsx
=> fix(client): fix client css

README.md, README.zh-CN.md
chore(docs): update readme img
=> chore(docs): update readme img

document/docs/zh/index.md
=> docs: fix link

.changeset/beige-horses-flow.md, .changeset/light-news-report.md, document/docs/en/guide/usage/bundle-overall.mdx, document/docs/zh/guide/usage/bundle-overall.mdx, packages/types/src/constants.ts
Support for counting woff and woff2 files in Bundle Overall's font files
close #152
=> feat(utils): bundle overall support woff/woff2 files

.changeset/calm-horses-travel.md, .husky/pre-commit, package.json, packages/sdk/package.json, packages/sdk/src/sdk/server/index.ts, packages/sdk/src/sdk/utils/openBrowser.ts, packages/sdk/static/openChrome.applescript
=> chore(sdk): reuse existing tab instead of creating a new one

document/rspress.config.ts
Update google analytics id, the current used id is for `rsbuild.dev`, and I have create a new id for `rsdoctor.dev`.
=> docs: update google analytics id

.changeset/friendly-years-occur.md, packages/types/package.json, packages/types/src/plugin/baseCompiler.ts, packages/types/src/plugin/baseLoader.ts, packages/types/src/sdk/config.ts, pnpm-lock.yaml
fix(types): rsdoctor types package change the dependency of @rspack/core.
=> fix(types): rsdoctor types package change the dependency of @rspack/core

.changeset/polite-lamps-itch.md, packages/core/src/build-utils/build/utils/loader.ts, packages/core/tests/build/utils/loader/__snapshots__/changeBuiltinLoader.test.ts.snap, packages/core/tests/build/utils/loader/changeBuiltinLoader.test.ts, packages/rspack-plugin/src/builtinLoaderPlugin.ts
fix(rspack):optimize the builtin:swc-loader matching calculation
closes:#166
=> fix(rspack):optimize the builtin:swc-loader matching calculation

packages/client/README.md, packages/components/README.md, packages/core/README.md, packages/graph/README.md, packages/rspack-plugin/README.md, packages/sdk/README.md, packages/test-helper/README.md, packages/types/README.md, packages/utils/README.md, packages/webpack-plugin/README.md
chore: optimize packages readme
=> chore: optimize packages readme

package.json, pnpm-lock.yaml
=> chore: update modern version

.gitattributes, .husky/post-checkout
https://github.com/web-infra-dev/modern.js/pull/2150
=> chore(infra): avoid pnpm-lock conflict

.changeset/hot-flies-help.md, packages/components/src/components/Alert/package-relation.tsx, packages/components/src/components/Alerts/common.tsx, packages/components/src/components/Layout/menus.tsx, packages/components/src/pages/Overall/index.tsx, packages/components/src/pages/Overall/responsiveGridList.tsx
=> fix(components): responsive Overall

document/docs/en/_meta.json, document/docs/en/config/_meta.json, document/docs/en/config/options/_meta.json, document/docs/en/config/options/options.mdx, document/docs/en/config/options/term.mdx, document/docs/en/guide/more/faq.mdx, document/docs/en/guide/start/_meta.json, document/docs/en/guide/start/cli.mdx, document/docs/en/guide/start/quick-start.mdx, document/docs/en/guide/usage/bundle-size.mdx, document/docs/en/guide/usage/loaders-analysis.mdx, document/docs/en/guide/usage/loaders-timeline.mdx, document/docs/en/guide/usage/resolver.mdx, document/docs/zh/_meta.json, document/docs/zh/config/_meta.json, document/docs/zh/config/options/_meta.json, document/docs/zh/config/options/options.mdx, document/docs/zh/config/options/term.mdx, document/docs/zh/guide/more/faq.mdx, document/docs/zh/guide/start/_meta.json, document/docs/zh/guide/start/cli.mdx, document/docs/zh/guide/start/quick-start.mdx, document/docs/zh/guide/usage/bundle-size.mdx, document/docs/zh/guide/usage/loaders-analysis.mdx, document/docs/zh/guide/usage/loaders-timeline.mdx, document/docs/zh/guide/usage/resolver.mdx
chore(docs): add cli Tutorial documentation
#7
=> chore(docs): add cli Tutorial documentation

.changeset/clean-comics-double.md, .changeset/eleven-tomatoes-taste.md, .changeset/fresh-paws-check.md, .changeset/hot-flies-help.md, .changeset/witty-parents-collect.md, packages/cli/CHANGELOG.md, packages/cli/package.json, packages/client/CHANGELOG.md, packages/client/package.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/graph/CHANGELOG.md, packages/graph/package.json, packages/rspack-plugin/CHANGELOG.md, packages/rspack-plugin/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, packages/types/CHANGELOG.md, packages/types/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json, packages/webpack-plugin/CHANGELOG.md, packages/webpack-plugin/package.json
- feat(cli): create @rsdoctor/cli package
- optimize(sdk): change the socket host url support the doctor used in devcontainer (Docker)
- fix(graph): dependency packages has some error.
- fix: no parsed/gziped size on 'Bundle Analyzer Graph' page error.
- fix(components): responsive Header Menu fix.
=> Release v0.1.2

README.md, README.zh-CN.md, document/docs/en/blog/release/release-note-1.mdx, document/docs/zh/blog/release/release-note-1.mdx
chore(docs): add credits for statoscope
=> chore(docs): add credits for statoscope

.changeset/healthy-icons-explode.md, packages/cli/package.json, pnpm-lock.yaml
fix(cli): fix lack of dependency error
=> fix(cli): the error of @rsdoctor/cli missing @rsdoctor/cli dependency.

document/docs/en/guide/more/faq.mdx, document/docs/en/guide/start/cli.mdx, document/docs/en/guide/start/quick-start.mdx, document/docs/zh/guide/more/faq.mdx, document/docs/zh/guide/start/quick-start.mdx
chore(docs): add next.js faq
mr: https://github.com/web-infra-dev/rsdoctor/issues/177
=> chore(docs): add next.js faq

.changeset/metal-seals-play.md, packages/core/src/inner-plugins/plugins/loader.ts
fix(rspack): rspack loader analysis error
#197
=> fix(rspack): rspack loader analysis error

.changeset/cool-starfishes-allow.md, packages/core/package.json, packages/core/src/inner-plugins/utils/config.ts, packages/rspack-plugin/package.json, packages/rspack-plugin/src/builtinLoaderPlugin.ts, packages/rspack-plugin/src/plugin.ts, packages/rspack-plugin/src/probeLoader.ts, packages/webpack-plugin/package.json, pnpm-lock.yaml
fix(core): optimize the package's dependencies to reduce the size of the packages.
=> fix(core): optimize the package's dependencies

.changeset/funny-chicken-beg.md, packages/client/package.json
packages/client   publish only dist files
=> fix(client): publish only dist files

.github/renovate.json5
Configure renovate to update dependencies, close https://github.com/web-infra-dev/rsdoctor/pull/213
https://developer.mend.io/github/web-infra-dev/rsdoctor
=> chore(workflow): configure renovate to update dependencies

packages/types/src/rule/code/E1004.ts
chore: fix the wrong of ECMA Version Check's rule explanation
close: #228
=> chore: fix the wrong of ECMA Version Check's rule explanation

.changeset/bright-kids-change.md
=> chore: change changeset's version minor to patch

packages/components/src/utils/data/base.ts, packages/components/src/utils/data/remote.ts, packages/components/src/utils/request.ts, packages/types/src/manifest.ts
=> feat: add clouddata for inner-rsdoctor

.changeset/late-crabs-work.md, packages/client/package.json, packages/components/package.json, packages/core/src/inner-plugins/utils/config.ts, packages/core/src/types/plugin.ts, packages/rspack-plugin/src/plugin.ts, packages/sdk/src/sdk/sdk/types.ts, packages/sdk/src/sdk/sdk/webpack.ts, packages/sdk/src/sdk/server/apis/renderer.ts, packages/sdk/src/sdk/server/index.ts, packages/webpack-plugin/src/plugin.ts, pnpm-lock.yaml
feat(inner-rsdoctor): add innerClientName for inner-rsdoctor
=> feat(inner-rsdoctor): add innerClientName for inner-rsdoctor

packages/core/src/inner-plugins/utils/config.ts, packages/core/src/types/plugin.ts, packages/rspack-plugin/src/plugin.ts, packages/sdk/src/sdk/sdk/types.ts, packages/sdk/src/sdk/sdk/webpack.ts, packages/sdk/src/sdk/server/apis/renderer.ts, packages/sdk/src/sdk/server/index.ts, packages/types/src/sdk/server/index.ts, packages/webpack-plugin/src/plugin.ts
feat(inner-rsdoctor): add innerClientPath for inner-rsdoctor
=> feat(inner-rsdoctor): add innerClientPath for inner-rsdoctor

.changeset/ten-readers-push.md, examples/modern-minimal/modern.config.ts, packages/components/src/components/BundleDiff/DiffContainer/assets.tsx, packages/components/src/components/BundleDiff/DiffContainer/cards.tsx, packages/components/src/components/BundleDiff/DiffContainer/changes.tsx, packages/components/src/components/BundleDiff/DiffContainer/constants.ts, packages/components/src/components/BundleDiff/DiffContainer/diff.tsx, packages/components/src/components/BundleDiff/DiffContainer/index.tsx, packages/components/src/components/BundleDiff/DiffContainer/modules.tsx, packages/components/src/components/BundleDiff/DiffContainer/overview.tsx, packages/components/src/components/BundleDiff/DiffContainer/packages.tsx, packages/components/src/components/BundleDiff/DiffContainer/row.tsx, packages/components/src/components/BundleDiff/DiffContainer/types.ts, packages/components/src/components/BundleDiff/DiffContainer/utils.tsx, packages/components/src/components/BundleDiff/DiffServerAPIProvider/index.tsx, packages/components/src/components/BundleDiff/constants.tsx, packages/components/src/components/BundleDiff/index.ts, packages/components/src/components/Card/index.tsx, packages/components/src/components/index.ts, packages/components/tsconfig.json, packages/sdk/src/sdk/server/apis/bundle-diff.ts, packages/types/src/sdk/server/apis/index.ts
feat(client): add bundle diff components
#178
=> feat(client): add bundle diff components

packages/components/src/components/index.ts
fix(client): export bundle diff components
=> fix(client): export bundle diff components

.changeset/giant-plums-sit.md, document/package.json, pnpm-lock.yaml
=> chore: upload rspress version

.changeset/giant-plums-sit.md, packages/cli/CHANGELOG.md, packages/cli/package.json, packages/client/CHANGELOG.md, packages/client/package.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/graph/CHANGELOG.md, packages/graph/package.json, packages/rspack-plugin/CHANGELOG.md, packages/rspack-plugin/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, packages/types/CHANGELOG.md, packages/types/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json, packages/webpack-plugin/CHANGELOG.md, packages/webpack-plugin/package.json
- feat: add Bundle diff components
=> Release v0.1.7

packages/types/src/manifest.ts
=> chore: add type cloudData

.changeset/gorgeous-suits-juggle.md, packages/rspack-plugin/package.json, pnpm-lock.yaml
fix(rspack-plugin): rspack plugin dependencies error
=> fix(rspack-plugin): rspack plugin dependencies error

.changeset/gorgeous-suits-juggle.md, .changeset/proud-fans-appear.md, packages/cli/CHANGELOG.md, packages/cli/package.json, packages/client/CHANGELOG.md, packages/client/package.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/document/CHANGELOG.md, packages/document/package.json, packages/graph/CHANGELOG.md, packages/graph/package.json, packages/rspack-plugin/CHANGELOG.md, packages/rspack-plugin/package.json, packages/sdk/CHANGELOG.md, packages/sdk/package.json, packages/types/CHANGELOG.md, packages/types/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json, packages/webpack-plugin/CHANGELOG.md, packages/webpack-plugin/package.json
- fix(rspack-plugin): rspack plugin dependencies error
- chore: migrate document to packages to publish @rsdoctor/docs
=> Release v0.1.8

examples/rsbuild-minimal/package.json, examples/rsbuild-minimal/rsbuild.config.ts, packages/client/package.json, packages/client/rsbuild.config.ts, pnpm-lock.yaml
=> chore(deps): bump Rsbuild v0.5

examples/modern-minimal/package.json, examples/modern-minimal/tsconfig.json, pnpm-lock.yaml
Update Modern.js example, remove some unused dependencies.
=> chore: update Modern.js example

.changeset/selfish-frogs-wash.md, packages/components/src/components/Configuration/builder.tsx, packages/document/docs/en/guide/usage/plugins-analysis.mdx, packages/document/docs/en/guide/usage/project-overall.mdx, packages/document/docs/zh/guide/usage/plugins-analysis.mdx, packages/document/docs/zh/guide/usage/project-overall.mdx
Correct "bundler config", Rspack and Webpack are bundlers.
=> fix: correct bundler config

.changeset/proud-fans-appear.md, packages/document/package.json
=> chore: publish document pkg

packages/document/package.json, packages/document/rspress.config.ts, packages/document/theme/pages/index.tsx, pnpm-lock.yaml
Fix the theme of homepage by upgrading Rspress and update some styles.
- Before:
- After:
=> docs: fix homepage theme

.changeset/weak-chairs-laugh.md, packages/utils/src/common/data/index.ts
fix(utils): GetModuleCodeByModuleIds sdk api
=> fix(utils): GetModuleCodeByModuleIds sdk api

.changeset/tiny-pumpkins-compete.md
chore(docs): inner rsdoctor document support
=> chore(docs): inner rsdoctor document support

examples/multiple-minimal/build.ts, examples/multiple-minimal/package.json, examples/multiple-minimal/src/app.tsx, examples/multiple-minimal/src/declaration.d.ts, examples/multiple-minimal/src/index.module.less, examples/multiple-minimal/src/index.ts, examples/multiple-minimal/tsconfig.json, pnpm-lock.yaml
chore(example): add webpack multi plugin example
=> chore(example): add webpack multi plugin example

packages/components/src/components/Layout/menus.tsx
fix(client): fix layout style ui
=> fix(client): fix layout style ui

packages/components/src/pages/BundleSize/components/asset.tsx, packages/document/docs/en/guide/start/quick-start-shared.mdx, packages/document/docs/zh/guide/start/quick-start-shared.mdx
Next.js should use webpack plugin, and fix another grammer issue.
=> docs: fix next.js code example

.changeset/cold-eagles-exercise.md
=> chore: add minor publish changeset

.changeset/cold-eagles-exercise.md
=> chore: publish the minor version.

packages/core/package.json, packages/utils/package.json
fix: @rsdoctor/core types exports
=> fix: @rsdoctor/core types exports

.changeset/sweet-ducks-beam.md
chore: add changeset for update
=> chore: add changeset for update

.changeset/sweet-ducks-beam.md, packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
* feat(plugin): add the analysis of tree-shaking feature by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/298
* fix: make ECMA check log more authentic by @chenjiahan in https://github.com/web-infra-dev/rsdoctor/pull/297
* fix(plugin): the error of analyzing the missing builtin loader when rspack uses dev mode by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/300
* fix(core): the types exports problem by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/305
* fix: @rsdoctor/core types exports by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/313
* fix: multi plugin rspack output path error by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/315
* docs: fix next.js code example by @jkzing in …
=> Release v0.2.1

.changeset/lemon-geckos-shop.md, packages/rspack-plugin/src/plugin.ts
fix: rspack multi plugin output error
=> fix: rspack multi plugin output error

packages/document/docs/en/guide/usage/_meta.json, packages/document/docs/en/guide/usage/rule-config.mdx, packages/document/docs/zh/guide/usage/_meta.json, packages/document/docs/zh/guide/usage/rule-config.mdx
chore(docs): rule config set
closes: #311
=> chore(docs): rule config set

packages/rspack-plugin/src/plugin.ts
fix(plugin): add error-plugin
closes: #240
=> fix(plugin): add error-plugin

packages/core/package.json, pnpm-lock.yaml
fix(core): change core package‘s @rsdoctor/types from dev to dependencien.
=> fix(core): change core package‘s @rsdoctor/types from dev to dependencien.

packages/document/package.json, pnpm-lock.yaml
- bump rspress and rsfamily-nav-icon
- fix the missing license of rsfamily-nav-icon.
=> docs: bump rspress and rsfamily-nav-icon

scripts/tsconfig/base.json
If you accept this pr I will be very happy, because it greatly facilitates my reading of the source code.
=> chore(tsconfig): Configure declarationMap to true

README.zh-CN.md
=> chore: fix readme error

.changeset/swift-crews-turn.md
=> chore: publish 0.2.4 version

.changeset/cold-dryers-live.md, packages/core/src/rules/rule.ts, packages/types/src/linter/diagnostic.ts
modify severity of rules dynamically at runtime
Closes #331
=> feat(core):  modify severity of rules dynamically at runtime

packages/client/rsbuild.config.ts, packages/client/tsconfig.json, packages/components/tsconfig.json, scripts/tsconfig/base.json
fix(config): fix some config problem
=> fix(config): fix some config problem

packages/cli/src/commands/analyze.ts
fix(cli): support for online data fetch
#344
=> fix(cli): support for online data fetch

.changeset/happy-points-visit.md
chore(upgrade): upgrade to the new version
=> chore(upgrade): upgrade to the new version

e2e/cases/doctor-rspack/banner-plugin.test.ts, packages/rspack-plugin/package.json, packages/rspack-plugin/src/plugin.ts, packages/webpack-plugin/package.json, pnpm-lock.yaml
fix(plugin): dpendcies problem
=> fix(plugin): dpendcies problem

e2e/cases/doctor-rspack/banner-plugin.test.ts, packages/rspack-plugin/src/plugin.ts
feat(plugin): open the banner plugin
=> feat(plugin): open the banner plugin

.changeset/fresh-gifts-yawn.md
=> chore: add changset for upgrade.

packages/document/docs/en/config/options/options.mdx, packages/document/docs/en/guide/usage/bundle-size.mdx, packages/document/docs/zh/config/options/options.mdx, packages/document/docs/zh/guide/usage/bundle-size.mdx
chore(docs): add bundle analysis's banner plugin documentition
https://github.com/web-infra-dev/rsdoctor/issues/345
=> chore(docs): add bundle analysis's banner plugin documentition

.changeset/flat-dogs-ring.md, packages/components/src/utils/data/local.ts, packages/components/src/utils/socket.ts
feat(sdk): socket protocol problem
=> feat(sdk): socket protocol problem

examples/rsbuild-minimal/package.json, pnpm-lock.yaml
fix https://github.com/web-infra-dev/rsdoctor/issues/350
=> chore: bump rsbuild to 0.7.2

packages/sdk/src/sdk/sdk/core.ts, packages/utils/package.json, packages/utils/src/build/envinfo.ts, pnpm-lock.yaml
Now we can get the pnpm version using the getpnpmInfo method
=> chore: Get the version of pnpm with getpnpmInfo

packages/rspack-plugin/package.json, packages/types/package.json, pnpm-lock.yaml
chore: change the peer dependencies version
=> chore: change the peer dependencies version

.changeset/wicked-weeks-vanish.md
=> chore: add changeset

packages/components/src/pages/BundleSize/components/asset.tsx, packages/graph/src/graph/module-graph/module.ts
fix(plugin): report code type error on rspack builder
=> fix(plugin): report code type error on rspack builder

examples/rsbuild-minimal/rsbuild.config.ts, packages/core/src/inner-plugins/utils/config.ts, packages/core/src/types/plugin.ts, packages/document/docs/en/config/options/options.mdx, packages/document/docs/zh/config/options/options.mdx, packages/rspack-plugin/src/plugin.ts, packages/webpack-plugin/src/plugin.ts
=> feat: support port

packages/core/src/build-utils/build/chunks/assetsModules.ts, packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts, packages/core/src/inner-plugins/utils/config.ts, packages/core/src/types/plugin.ts
feat(plugin): add no parse bundle options
=> feat(plugin): add no parse bundle options

.github/renovate.json5
chore: update renovate ignore list
=> chore: update renovate ignore list

examples/rspack-minimal/package.json, pnpm-lock.yaml
chore: update the examples's version
=> chore: update the examples's version

packages/document/docs/404.mdx, packages/document/docs/public/netlify.toml
add 404 page to document website
https://github.com/web-infra-dev/rsbuild/pull/2585
=> docs: add 404 page and netlify redirect

packages/types/src/constants.ts
optimize: Exclude .css.map calculation size
=> optimize: Exclude .css.map calculation size

packages/components/src/utils/size.ts
fix: client size unit change 1024 to 1000
Align rsbuild and rspack unit conversion.
=> chore: client size unit change 1024 to 1000

.changeset/few-baboons-count.md
=> chore(upgrade): add changeset to 0.3.4

e2e/cases/doctor-rspack/plugin.test.ts, e2e/package.json, examples/modern-minimal/package.json, examples/rsbuild-minimal/package.json, examples/rspack-banner-minimal/package.json, examples/rspack-minimal/package.json, package.json, packages/client/package.json, packages/client/rsbuild.config.ts, packages/core/package.json, packages/core/src/inner-plugins/plugins/loader.ts, packages/core/src/inner-plugins/plugins/plugins.ts, packages/core/src/inner-plugins/plugins/progress.ts, packages/core/src/types/plugin.ts, packages/document/package.json, packages/rspack-plugin/package.json, packages/rspack-plugin/src/plugin.ts, packages/rspack-plugin/src/probeLoaderPlugin.ts, packages/types/package.json, packages/types/src/plugin/baseCompiler.ts, packages/utils/src/common/loader.ts, pnpm-lock.yaml, scripts/test-helper/package.json, scripts/update-packages/package.json
refactor(types): refactor base types for BaseCompiler and BaseCompilation for the latest Rspack@0.7.5
#288
=> refactor(types): rewrite base types for BaseCompiler and BaseCompilation

.changeset/tricky-otters-pretend.md
chore(upgrade): add changeset for the  0.3.5
=> chore(upgrade): add changeset for the  0.3.5

examples/rsbuild-minimal/package.json, examples/rsbuild-minimal/rsbuild.config.ts, examples/rsbuild-minimal/rules/assets-count-limit.ts, packages/document/docs/en/guide/_meta.json, packages/document/docs/en/guide/custom/_meta.json, packages/document/docs/en/guide/custom/rule-custom.mdx, packages/document/docs/en/guide/custom/upload-data.mdx, packages/document/docs/zh/guide/_meta.json, packages/document/docs/zh/guide/custom/_meta.json, packages/document/docs/zh/guide/custom/rule-custom.mdx, packages/document/docs/zh/guide/custom/upload-data.mdx, pnpm-lock.yaml
chore(docs): add Linter documents
=> chore(docs): add Linter documents

packages/client/package.json
chore: @rsdoctor/client add MIT in package.json
=> chore: @rsdoctor/client add MIT in package.json

examples/modern-minimal/package.json, package.json, packages/components/src/pages/BundleSize/components/index.tsx, packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts, packages/core/src/inner-plugins/utils/config.ts, packages/core/src/types/plugin.ts, packages/rspack-plugin/src/plugin.ts, pnpm-lock.yaml
feat: support to open/close the generating of tile graph
=> feat: support to open/close the generating of tile graph

packages/document/docs/en/config/options/options.mdx, packages/document/docs/zh/config/options/options.mdx
chore(docs): add generate tile graph doc
=> chore(docs): add generate tile graph doc

.changeset/tough-spoons-retire.md
=> chore: add chageset

README.md, README.zh-CN.md
=> docs: remove underlines between badges

.changeset/shiny-grapes-draw.md
=> chore: add changesets

packages/utils/src/build/json.ts
fix: json stringfy some useless code
=> fix: json stringfy some useless code

packages/components/src/pages/BundleSize/components/asset.tsx
fix(client): module code show error
#429
=> fix(client): module code show error

.changeset/giant-months-try.md, .changeset/twelve-mice-tickle.md
=> Chore:update rsdoctor 0.3.10

README.md, README.zh-CN.md, scripts/dictionary.txt
=> docs: add Rslib links

packages/document/package.json, packages/document/theme/components/ToolStack.tsx, packages/document/theme/index.tsx, pnpm-lock.yaml
bump `@rstack-dev/doc-ui` to add Rslib and awesome Rspack
=> docs: bump `@rstack-dev/doc-ui` to add Rslib and awesome Rspack

packages/core/src/inner-plugins/plugins/bundleTagPlugin.ts, packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts, packages/core/src/inner-plugins/plugins/loader.ts
fix(loader): proxy loader no module error
=> fix(loader): proxy loader no module error

examples/rsbuild-minimal/rsbuild.config.ts, packages/client/rsbuild.config.ts, packages/client/src/router.tsx, packages/components/src/components/Alert/package-relation.tsx, packages/components/src/components/Loader/Analysis/files.tsx, packages/components/src/components/Loader/Analysis/index.tsx, packages/components/src/pages/TreeShaking/index.tsx, packages/components/src/pages/WebpackLoaders/Analysis/index.tsx, packages/core/src/inner-plugins/utils/config.ts, packages/core/src/types/plugin.ts, packages/graph/src/graph/chunk-graph/asset.ts, packages/graph/src/graph/module-graph/module.ts, packages/rspack-plugin/src/plugin.ts, packages/sdk/src/sdk/sdk/webpack.ts, packages/types/src/sdk/instance.ts, packages/types/src/sdk/module.ts
feat: add mode options & brief mode
#408
=> feat: add mode options & brief mode

packages/document/package.json, packages/document/theme/components/ToolStack.module.scss, packages/document/tsconfig.json, pnpm-lock.yaml
https://github.com/web-infra-dev/rspack/pull/7771
https://github.com/web-infra-dev/rsbuild/pull/3349
https://github.com/web-infra-dev/rspress/pull/1384
https://github.com/web-infra-dev/rsdoctor/pull/497
=> chore(deps): upgrade @rstack-dev/doc-ui 1.4.2

.changeset/stupid-comics-mate.md, packages/sdk/src/sdk/sdk/webpack.ts, packages/webpack-plugin/src/plugin.ts
fix(sdk): saveManifest need await when brief mode
=> fix(sdk): saveManifest need await when brief mode

packages/core/src/build-utils/build/module-graph/webpack/transform.ts
Reverted to the fallback to empty string that was there previously.
https://github.com/web-infra-dev/rsdoctor/discussions/502
https://github.com/web-infra-dev/rsdoctor/pull/102/files#diff-8896c65f442681aa3a88302753feb1a4e21afdf20c20579113876dbba4cd4083L176
=> Fix TypeError [ERR_INVALID_ARG_TYPE]

.changeset/breezy-deers-leave.md
=> chore: update changesets

packages/components/src/components/Alerts/common.tsx
Add sort duplicate packages
Old:
New:
#469
=> feat: add sort package-relation by desc

packages/document/docs/404.mdx, packages/document/package.json, packages/document/rspress.config.ts, pnpm-lock.yaml
1. 404.mdx can be automatically generated by rspress
2. pageType: 404 has a bug now
3. open `ssg: { strict: true }`
=> docs(fix): should use ssr for document

.github/renovate.json5
=> chore: update renovate list

.gitignore, examples/rspack-banner-minimal/rspack.config.js, packages/core/src/inner-plugins/plugins/bundleTagPlugin.ts, packages/core/src/inner-plugins/utils/config.ts
fix(core): banner plugin switch error
=> fix(core): banner plugin switch error

packages/components/src/components/Layout/index.tsx, packages/components/src/config.tsx, pnpm-lock.yaml
Support hidden Header by Context value.
=> feat: add new context field to support embedded rsdoctor to other page

packages/document/docs/en/guide/usage/bundle-diff.mdx, packages/document/docs/zh/guide/usage/bundle-diff.mdx
chore(docs): fix bundle-diff documents
=> chore(docs): fix bundle-diff documents

packages/document/docs/en/guide/more/faq.mdx, packages/document/docs/zh/guide/more/faq.mdx
chore(docs): rsdoctor add the note for CssExtractRspackPlugin.
=> chore(docs): rsdoctor add the note for CssExtractRspackPlugin

packages/document/package.json, packages/document/rspress.config.ts, pnpm-lock.yaml
https://github.com/web-infra-dev/rspress/pull/1472
=> docs: add sitemap rss and bump rspress

packages/core/src/inner-plugins/utils/config.ts
fix(core): normallize the reportCodeType error
=> fix(core): normallize the reportCodeType error

.changeset/itchy-shrimps-exercise.md
chore(update): add changesets for 0.4.7
=> chore(update): add changesets for 0.4.7

packages/cli/src/commands/bundle-diff.ts, packages/components/src/utils/data/local.ts, packages/components/src/utils/socket.ts, packages/sdk/src/sdk/sdk/webpack.ts, packages/sdk/src/sdk/server/index.ts, packages/types/src/manifest.ts
fix: the problem of socket host when use ip:port url.
=> fix: the problem of socket host when use ip:port url

packages/document/docs/zh/config/options/options-shared.mdx, packages/document/docs/zh/config/options/options.mdx
=> docs: fix typo

packages/components/src/components/Layout/index.tsx, packages/components/src/utils/locale.ts, packages/components/src/utils/storage.tsx
=> feat: Automatically switch language when first visit

packages/utils/src/common/graph/assets.ts
This pull request includes changes to the `packages/utils/src/common/graph/assets.ts` file to improve the handling of asset extensions. The most important changes are the addition of a new utility function to extract file extensions and the enhancement of an existing function to better match asset extensions.
Enhancements to asset extension handling:
* [`packages/utils/src/common/graph/assets.ts`](diffhunk://#diff-34f17e66263871c04e9f6bad6269547a376f28d27243870ebc1135dcfa7ca217R383-R390): Added a new function `extname` to extract the file extension from a filename, ignoring query parameters.
* [`packages/utils/src/common/graph/assets.ts`](diffhunk://#diff-34f17e66263871c04e9f6bad6269547a376f28d27243870ebc1135dcfa7ca217L43-R43): Modified the `isAssetMatchExtension` function to use the new …
=> fix: file Extension util

.husky/post-checkout, .husky/pre-commit, package.json
This pull request includes changes to the Husky configuration and the `package.json` file to streamline the setup process and remove unnecessary commands.
Changes to Husky configuration:
* [`.husky/post-checkout`](diffhunk://#diff-0658448ef4d719b66d40e2dfde5ead84ee1bd22e27404ac1d5fbb6e932cdc366L2): Removed the line that 
sources the Husky script as it is no longer needed.
* [`.husky/pre-commit`](diffhunk://#diff-d2bc4bbf14eadc292d84e0ef5f7a93115c23557f533809fc80b896934291529dL2): Removed the line that sources the Husky script as it is no longer needed.
Changes to `package.json`:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L19-R19): Simplified the `prepare` script by removing the `husky install` command, which is no longer necessary. …
=> chore: migrate husky

.changeset/eleven-ligers-attack.md, packages/sdk/package.json, packages/sdk/src/sdk/sdk/core.ts, packages/sdk/src/sdk/sdk/index.ts, packages/utils/src/common/algorithm.ts, pnpm-lock.yaml
This pull request introduces the `json-cycle` library to handle circular references in JSON data and includes improvements to error handling in the `compressText` function. The most important changes are summarized below:
* Added `json-cycle` to `dependencies` in `packages/sdk/package.json`.
* Imported `json-cycle` in `packages/sdk/src/sdk/sdk/core.ts` and `packages/sdk/src/sdk/sdk/index.ts` [[1]](diffhunk://#diff-6f861532af981b08531a1a092933d4b1aaf40b0c318148d374762cb778937b30R8) [[2]](diffhunk://#diff-fbc3e075b887be8e6c101b9df3c318be354defe14e244ffedd499d7f48a7a881R15).
* Updated JSON stringification to use `json-cycle` for handling circular references in `packages/sdk/src/sdk/sdk/core.ts` and `packages/sdk/src/sdk/sdk/index.ts` …
=> fix: circular configs options data

.github/renovate.json5
=> chore: renovate ignore

.changeset/cyan-falcons-dance.md
chore(upgrade): add changesets for 0.4.11
=> chore(upgrade): add changesets for 0.4.11

.github/ISSUE_TEMPLATE/1-bug-report.en-US.yml, .github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
> Issues types allow you to classify and manage your issues with a shared and consistent language across all repositories in the organization, such as bugs or tasks.
https://github.com/orgs/community/discussions/139933
=> chore(workflow): set Issue types

.changeset/nasty-lemons-argue.md
chore: add changesets for 0.4.12
=> chore: add changesets for 0.4.12

.github/workflows/release.yml
Remove all issue_comment trigger for security.
=> chore(CI): remove issue_comment trigger

packages/components/src/utils/request.ts
fix(client): the problem of the client's HMR
=> fix(client): the problem of the client's HMR

packages/document/docs/en/guide/start/intro.mdx
Change full stop to comma.
N/A
=> docs: fix grammar

package.json
=> fix: dev:doc script

.github/workflows/lint.yml, .github/workflows/test-ubuntu.yml, .github/workflows/test-windows.yml, pnpm-lock.yaml
chore: add release-* branch workflows
=> chore: add release-* branch workflows

e2e/cases/doctor-rspack/fixtures/loaders/esm/package.json, examples/modern-minimal/package.json, examples/multiple-minimal/package.json, examples/rsbuild-minimal/package.json, examples/webpack-minimal/package.json, package.json, packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/core/tests/fixtures/assets/webpack-stats.json, packages/document/package.json, packages/graph/package.json, packages/graph/tests/fixture/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json, scripts/test-helper/package.json
=> release: v0.4.13

e2e/cases/doctor-webpack/plugins/loader.test.ts, packages/core/src/build-utils/build/module-graph/webpack/transform.ts, packages/core/src/build-utils/build/utils/loader.ts, packages/core/src/build-utils/common/webpack/compatible.ts, packages/core/src/inner-plugins/plugins/loader.ts, packages/core/src/inner-plugins/plugins/summary.ts, packages/utils/src/common/summary.ts
Remove some legacy webpack 4 compatibility code to improve code maintainability.
=> fix: remove legacy webpack 4 compatibility code

packages/components/src/components/Charts/utils.ts, packages/components/src/components/Configuration/builder.tsx, packages/components/src/components/Loader/Analysis/files.tsx, packages/components/src/components/Loader/executions.tsx, packages/components/src/components/Opener/code.tsx, packages/components/src/components/Select/index.scss, packages/components/src/components/Select/index.tsx, packages/components/src/pages/BundleSize/components/index.module.scss, packages/components/src/pages/WebpackPlugins/index.scss, packages/components/src/pages/WebpackPlugins/index.tsx
=> fix(ui): fix some ui problems

packages/client/package.json, packages/client/rsbuild.config.ts, packages/sdk/package.json, packages/sdk/src/sdk/server/index.ts, pnpm-lock.yaml
chore: change the sirv to serve-static
=> chore: change the sirv to serve-static

packages/components/package.json, packages/components/src/components/Layout/menus.tsx, packages/components/src/components/Layout/progress.tsx, packages/components/src/pages/BundleSize/components/index.module.scss, packages/components/src/pages/BundleSize/components/index.tsx, packages/components/src/pages/ModuleAnalyze/components/fileTreeCom.scss, packages/components/src/pages/ModuleAnalyze/components/fileTreeCom.tsx, packages/components/src/pages/ModuleAnalyze/index.scss, packages/components/src/pages/ModuleAnalyze/index.tsx, packages/components/src/pages/Overall/index.tsx, packages/components/src/pages/WebpackPlugins/index.tsx, pnpm-lock.yaml
fix(UI): Overall & Bunlde page ui problem
- Skeleton problem
before:
after:
- indent problem
-  change the assets tree, because the UI desiagn has changed:
- optimize the module analysis page
- and some others ui bug fix.
=> fix(UI): Overall & Bunlde page ui problem

packages/components/src/components/Layout/header.tsx
chore(ui): change website logo.
=> feat(ui): update website logo

pnpm-lock.yaml
https://github.com/web-infra-dev/rsdoctor/actions/runs/12741470029/job/35508107970
=> fix: broken `pnpm-lock.yaml`

packages/components/src/components/Alerts/collapse.tsx, packages/components/src/components/Card/size.module.scss, packages/components/src/components/Loader/Analysis/files.tsx, packages/components/src/pages/BundleSize/components/cards.tsx
fix(ui): the overall  ui problem
when innerWidth < 1500, the style is messy.
before：
after：
before
after
=> fix(ui): the overall  ui problem

e2e/cases/doctor-rspack/fixtures/loaders/esm/package.json, examples/modern-minimal/package.json, examples/multiple-minimal/package.json, examples/rsbuild-minimal/package.json, examples/webpack-minimal/package.json, packages/core/tests/fixtures/assets/webpack-stats.json, packages/graph/tests/fixture/package.json, scripts/test-helper/package.json
chore: demos package.json add private:true
=> chore: demos package.json add private:true

package.json, packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
This pull request includes changes to multiple `package.json` files across various packages, primarily focused on updating the version numbers to `1.0.0-alpha` and adding a new script command.
Script additions:
* Added a new script command `"bump": "changeset version"` to `package.json`.
=> release: v1.0.0-alpha.0

packages/core/src/build-utils/build/chunks/assetsModules.ts, packages/core/src/build-utils/build/utils/parseBundle.ts, packages/core/src/build-utils/common/chunks/assetsModules.ts, packages/core/src/build-utils/common/module-graph/transform.ts, packages/core/src/build-utils/common/trans-utils/transStats.ts, packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts, packages/core/src/types/chunks.ts, packages/core/tests/build/utils/parseBundle.test.ts, packages/graph/src/graph/chunk-graph/graph.ts, packages/graph/src/graph/module-graph/graph.ts, packages/graph/src/graph/module-graph/module.ts, packages/types/src/sdk/module.ts
Use module graph and chunk graph to parse bundle.
=> refactor: use graph data to parse bundle

README.md
=> docs: add preview video to README.md

README.zh-CN.md
=> docs: add preview video to README.zh-CN.md

README.md, README.zh-CN.md
update Rslib description in README.md
=> chore: update Rslib description in README.md

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
=> release: 1.0.0-alpha.1

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
=> release: 1.0.0-alpha.2

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
=> release: v1.0.0-alpha.4

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
* feat: support cross chunks package rule by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/758
* fix(sdk): the error of websocket by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/755
* fix: summary loader consuming time of dirs by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/756
* docs: use Rstack unified homepage by @chenjiahan in https://github.com/web-infra-dev/rsdoctor/pull/757
* release: v1.0.0-alpha.4 by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/750
* chore(deps): update all patch dependencies by @renovate in https://github.com/web-infra-dev/rsdoctor/pull/753
* chore(deps): update dependency prettier to ^3.5.1 by @renovate in https://github.com/web-infra-dev/rsdoctor/pull/754
* chore: fix the broken pnpm-lock.yaml by …
=> release: 1.0.0-beta.0

packages/components/src/pages/BundleSize/components/index.module.scss, packages/components/src/pages/BundleSize/components/index.tsx, packages/components/src/pages/BundleSize/components/search-modal.tsx, packages/types/src/sdk/server/apis/graph.ts, packages/types/src/sdk/server/apis/index.ts, packages/utils/src/common/data/index.ts
[Feature] support search module in all chunks.
=> feat: support search module in all chunks

packages/utils/src/common/loader.ts
=> fix: loader page ui problem

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
release 1.0.0-beta.1
* feat: support search module in all chunks by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/763
* fix: optimize the display of loader name by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/765
* fix: loader page ui problem by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/766
* fix(ui): The file tree elements have problems with keyword searches. by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/767
* release: 1.0.0-beta.0 by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/764
**Full Changelog**: https://github.com/web-infra-dev/rsdoctor/compare/v1.0.0-beta.0...v1.0.0-beta.1
=> release 1.0.0-beta.1

packages/components/src/components/Alerts/bundle-alert.tsx
=> fix(ui): overall's bundle alerts

packages/document/docs/en/config/options/options.mdx, packages/document/docs/zh/config/options/options.mdx
=> docs: change options document

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
* feat: support rspack native plugin by @LingyuCoder in https://github.com/web-infra-dev/rsdoctor/pull/710
* fix(ui): overall's bundle alerts by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/770
* docs: add rules documents by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/775
* docs: change options document by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/777
* release 1.0.0-beta.1 by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/768
* chore: bump rspack to 1.2.5 by @LingyuCoder in https://github.com/web-infra-dev/rsdoctor/pull/769
* chore(deps): update dependency @changesets/cli to ^2.28.1 by @renovate in https://github.com/web-infra-dev/rsdoctor/pull/774
* chore(deps): update all patch dependencies by @renovate in …
=> Release 1.0.0-beta.2

packages/components/src/components/Alerts/bundle.tsx, packages/components/src/components/Alerts/list.tsx, packages/core/src/rules/rules/loader-performance-optimization/index.ts, packages/core/src/rules/rules/loader-performance-optimization/types.ts
fix: the problem of loader-performance-optimization rule
=> fix: the problem of loader-performance-optimization rule

packages/components/src/pages/BundleSize/components/asset.tsx
| Before | After |
| - | - |
| <img width="315" alt="Screenshot 2025-03-04 at 1 58 51 PM" src="https://github.com/user-attachments/assets/b88c774a-1ee2-4a17-8239-1abc46491ef6" /> | <img width="312" alt="Screenshot 2025-03-04 at 2 06 26 PM" src="https://github.com/user-attachments/assets/bee46770-23aa-43ea-818d-f83c8c65c917" /> |
=> fix(ui): add spacing before size value

packages/document/docs/en/guide/usage/bundle-size.mdx, packages/document/docs/zh/guide/usage/bundle-size.mdx
docs: optimize the rsdoctor's bundle size document
=> docs: optimize the rsdoctor's bundle size document

e2e/package.json, examples/rspack-banner-minimal/package.json, examples/rspack-layers-minimal/package.json, examples/rspack-minimal/package.json, packages/core/package.json, packages/rspack-plugin/package.json, packages/types/package.json, pnpm-lock.yaml, scripts/test-helper/package.json
=> bump rspack 1.2.7

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
* feat(ui): improve tree graph tooltip by @charpeni in https://github.com/web-infra-dev/rsdoctor/pull/790
* fix: the problem of loader-performance-optimization rule by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/779
* fix: eco ci pnpm error when install. by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/784
* fix(ui): add spacing between tile graph disabled and the link by @charpeni in https://github.com/web-infra-dev/rsdoctor/pull/793
* fix(ui): add spacing before the modules count by @charpeni in https://github.com/web-infra-dev/rsdoctor/pull/792
* fix(ui): add spacing before size value by @charpeni in https://github.com/web-infra-dev/rsdoctor/pull/791
* fix: compressData options problem by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/796
* …
=> release v1.0.0-beta.3

examples/rsbuild-minimal/rsbuild.config.ts, examples/rspack-banner-minimal/src/index.tsx, examples/rspack-layers-minimal/src/index.tsx, examples/rspack-minimal/src/index.tsx
Fix incorrect import and config at examples
=> chore(example): fix incorrect import and config

packages/document/rspress.config.ts
=> docs: add edit-link

packages/document/docs/zh/config/options/options.mdx
Format Rsdoctor options zh desc.
=> docs: format Rsdoctor options zh desc

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
=> release: 1.0.0-rc.0

packages/document/docs/en/config/options/options.mdx, packages/document/docs/en/guide/more/faq.mdx
While reading the docs, I noticed one case where a translation was missing.
=> docs: translate faq example

packages/components/src/pages/BundleSize/components/asset.tsx
fix: the bundled size of the folder is wrong
- before
- after
=> fix: the bundled size of the folder is wrong

packages/components/src/pages/BundleSize/components/asset.tsx, packages/components/src/pages/BundleSize/components/index.module.scss
=> optimize: the ui style of bundle size tree

packages/components/src/pages/BundleSize/components/index.module.scss
optimize: the ui problem of bundle size tree
=> optimize: the ui problem of bundle size tree

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
See https://github.com/web-infra-dev/rsdoctor/releases/tag/v1.0.0
=> Release:  v1.0

packages/document/docs/en/blog/release/release-note-1_0.mdx, packages/document/docs/zh/blog/release/release-note-1_0.mdx
Polish release blog:
- Made the content easier to understand
- Adjusted the order of paragraphs
- Fixed some terminology
=> docs: polish release blog

README.md, README.zh-CN.md, packages/document/docs/en/blog/release/release-note-1_0.mdx, packages/document/docs/en/guide/start/intro.mdx, packages/document/docs/zh/blog/release/release-note-0_1.mdx, packages/document/docs/zh/blog/release/release-note-1_0.mdx, packages/document/docs/zh/guide/start/intro.mdx
Update introduction to be consistent with the 1.0 release blog: https://rsdoctor.dev/blog/release/release-note-1_0
=> docs: update introduction

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
* feat: add assets gzipsize by @akbq2008 in https://github.com/web-infra-dev/rsdoctor/pull/833
* fix: update `supports.banner` logs by @chenjiahan in https://github.com/web-infra-dev/rsdoctor/pull/831
* fix: the problem when use mini-css-extract-plugin loader by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/840
* docs: add v1.0 release note by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/781
* docs: polish release blog by @chenjiahan in https://github.com/web-infra-dev/rsdoctor/pull/829
* docs: update introduction by @chenjiahan in https://github.com/web-infra-dev/rsdoctor/pull/830
* docs: cleanup README files by @chenjiahan in https://github.com/web-infra-dev/rsdoctor/pull/832
* Release:  v1.0 by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/828 …
=> release: v1.0.1

packages/ai/package.json, packages/ai/src/mcp/index.ts, packages/ai/src/mcp/server.ts, packages/ai/src/model/index.ts, pnpm-lock.yaml
This pull request includes multiple changes to enhance logging, update dependencies, and refactor the code for better maintainability. The most important changes include updating the `package.json` dependencies, refactoring the main function in `index.ts`, and integrating a new logging system.
* [`packages/ai/package.json`](diffhunk://#diff-3758ea4fd63e4789bf712baab7b4b0227fce843a17e2ed535091b9c3b83ff2dfL26-R41): Updated dependencies and devDependencies to include `@modelcontextprotocol/sdk`, `@rsdoctor/utils`, and `socket.io-client`, and removed redundant entries.
* [`packages/ai/src/mcp/index.ts`](diffhunk://#diff-d5033535c52ec8626acd16e32ec55a9d336afc041757bf8aea3f5e2d25e01d3cL1-R16): Refactored the `main` function to accept a model configuration, added error handling for missing model …
=> feat: ai support qwen

packages/core/src/inner-plugins/utils/config.ts, packages/core/src/types/plugin.ts, packages/rspack-plugin/src/multiple.ts, packages/rspack-plugin/src/plugin.ts, packages/types/src/sdk/instance.ts, packages/webpack-plugin/src/multiple.ts, packages/webpack-plugin/src/plugin.ts
fix: delete some unuse options
This pull request includes updates to multiple package versions and the removal of the `disableTOSUpload` option from various configurations. The most important changes include version updates across several packages and codebase simplification by removing the `disableTOSUpload` option.
Codebase simplification:
* [`packages/core/src/inner-plugins/utils/config.ts`](diffhunk://#diff-0bc1a98d5cf2810e43077f2e07c17dced9b44cbbb6f1f19e517f4bdcfd222015L34): Removed `disableTOSUpload` option from `normalizeUserConfig` function. [[1]](diffhunk://#diff-0bc1a98d5cf2810e43077f2e07c17dced9b44cbbb6f1f19e517f4bdcfd222015L34) [[2]](diffhunk://#diff-0bc1a98d5cf2810e43077f2e07c17dced9b44cbbb6f1f19e517f4bdcfd222015L129)
* …
=> fix: delete some unuse options

packages/components/src/components/CodeViewer/diff.tsx
=> fix: Cleans up diff editor on unmount

packages/components/src/components/FileTree/index.scss, packages/components/src/pages/BundleSize/components/index.module.scss, packages/components/src/pages/Overall/index.module.scss
=> feat(ui): optimize treeNode style

packages/components/src/components/Loader/Analysis/files.tsx, packages/components/src/components/Loader/Analysis/index.tsx, packages/components/src/components/Loader/Analysis/style.module.scss
**Background**
While browsing the loaders-analysis page, I noticed several UI issues with the file tree component. The layout is misaligned, lacks responsiveness, and interactive elements don't have proper cursor indicators (missing `cursor: pointer`). And I found that some layout logic relies on `window.innerWidth` for calculations, which is not an optimal approach.
**Improvements**
1. Remove logic that uses `window.innerWidth` to calculate element widths, and replace it with a flex-based layout
1. Implement proper alignment logic and fix existing horizontal alignment issues
1. Add min-width settings - set content width to minimum 900px with horizontal scrolling when viewport is 1. narrower, providing better UI experience based on average content width
1. Add `cursor: pointer` to all …
=> feat: analysis filetree UI

packages/document/docs/en/guide/start/quick-start-shared.mdx, packages/document/docs/zh/guide/start/quick-start-shared.mdx
docs: optimize the docs for using rsdoctor in the Next.js + Rspack build scenario
=> docs: optimize the docs for using rsdoctor in the Next.js + Rspack

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
* feat: UI execution diff view add side-by-side check by @quanquan2100 in https://github.com/web-infra-dev/rsdoctor/pull/912
* feat(ui): optimize treeNode style by @luhc228 in https://github.com/web-infra-dev/rsdoctor/pull/938
* feat: analysis filetree UI by @quanquan2100 in https://github.com/web-infra-dev/rsdoctor/pull/923
* feat: module instance add issuerPath by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/969
* fix: delete some unuse options by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/894
* fix: Cleans up diff editor on unmount by @quanquan2100 in https://github.com/web-infra-dev/rsdoctor/pull/913
* fix: bump rspack 1.3.5 and fix rspack types by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/1016
* docs: optimize the docs for using …
=> Release v1.0.2

packages/ai/src/prompt/bundle.ts, packages/ai/src/server/server.ts, packages/ai/src/server/tools.ts, packages/client/rsbuild.config.ts, packages/sdk/package.json, pnpm-lock.yaml
support get_rule_info tool and get_similar_packages
=> feat: support get_rule_info tool and get_similar_packages

scripts/test-helper/package.json
=> fix(@scripts/test-helper): fix type path error

packages/ai/package.json, packages/ai/src/prompt/bundle.ts, packages/ai/src/server/server.ts, packages/ai/src/server/tools.ts, packages/client/rsbuild.config.ts, packages/sdk/package.json, packages/types/src/sdk/server/apis/index.ts, packages/utils/src/common/data/index.ts
=> optimize：ai tools mcp bundls optimize

packages/types/src/rule/code/E1001.ts
Improves the clarity of rule `E1001`.
=> fix: improve clarity of rule `E1001`

e2e/package.json, examples/modern-minimal/package.json, examples/multiple-minimal/package.json, examples/rspress-minimal/package.json, examples/webpack-minimal/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json, pnpm-lock.yaml, scripts/test-helper/package.json
=> chore(deps): update @types/node to ^22.8.1

packages/components/package.json, packages/types/package.json, pnpm-lock.yaml
chore: change the @rsdoctor/components dependencies
=> chore: change the @rsdoctor/components dependencies

e2e/cases/doctor-rspack/banner-plugin.test.ts, e2e/cases/doctor-rspack/brief.test.ts, e2e/cases/doctor-rspack/bundle-diff.test.ts, e2e/cases/doctor-rspack/layer-plugin.test.ts, e2e/cases/doctor-rspack/linter-rule-render.test.ts, e2e/cases/doctor-rspack/plugin.test.ts, e2e/cases/doctor-rspack/tag-plugin-without-banner.test.ts, e2e/cases/doctor-rspack/test-utils.ts, e2e/test-kit/index.ts, e2e/tsconfig.json, pnpm-lock.yaml
test: the test problem for bundle diff page.
1. fix the test problem for bundle diff page.
After merging this MR (https://github.com/web-infra-dev/rsdoctor/pull/1044), the tests started failing with the following error. The issue could not be reproduced locally, and after checking the `bundle diff` page, no problems were found. Therefore, the tests related to the `bundle diff` section were temporarily disabled(file: e2e/cases/doctor-rspack/bundle-diff.test.ts).
2. fix the `MaxListenersExceededWarning: Possible EventEmitter memory leak detected.`
=> test: the test problem for bundle diff page

packages/utils/src/build/server.ts
=> fix(server): avoid using browser-restricted port numbers

packages/ai/README.md, packages/ai/README.zh-CN.md
docs: optimize the documentation of the rsdoctor-mcp-server
=> docs: optimize the documentation of the rsdoctor-mcp-server

README.md, README.zh-CN.md, packages/document/docs/en/guide/start/intro.mdx, packages/document/docs/zh/guide/start/intro.mdx, packages/document/package.json, pnpm-lock.yaml, scripts/dictionary.txt
This PR adds a new "Rstack" section to the README files , which details the projects of the Rstack toolchain and helps users to understand its concepts and goals.
Same as https://github.com/web-infra-dev/rspack/pull/10424
=> docs: update Rstack introduction

e2e/cases/doctor-rspack/linter-rule-render.test.ts, e2e/cases/doctor-rspack/plugin.test.ts, e2e/package.json, pnpm-lock.yaml
=> chore: add some logs to e2e

packages/core/src/build-utils/build/module-graph/webpack/transform.ts
remove unexpected test code when NODE_ENV is test.
before:
after:
=> fix: remove unexpected test code when NODE_ENV is test

e2e/cases/doctor-rspack/banner-plugin.test.ts, e2e/package.json, packages/core/src/inner-plugins/plugins/bundleTagPlugin.ts, pnpm-lock.yaml
fix: add info for banner plugin when drop_console is true
=> fix: add info for banner plugin when drop_console is true

packages/ai/package.json
release @rsdoctor/mcp-server 0.0.1
=> release @rsdoctor/mcp-server 0.0.1

packages/components/src/pages/BundleSize/components/asset.tsx, packages/components/src/pages/ModuleAnalyze/fileTree.tsx, packages/components/src/pages/ModuleAnalyze/index.tsx, packages/core/src/build-utils/common/module-graph/transform.ts, packages/core/tests/common/module-graph/__snapshots__/transform.test.ts.snap, packages/graph/src/graph/module-graph/module.ts, packages/types/src/plugin/baseStats.ts, packages/types/src/sdk/module.ts
=> feat: support bailout_reason

e2e/package.json, examples/rspack-banner-minimal/package.json, examples/rspack-layers-minimal/package.json, examples/rspack-minimal/package.json, packages/core/package.json, packages/rspack-plugin/package.json, packages/types/package.json, pnpm-lock.yaml, scripts/test-helper/package.json
=> chore(deps): bump rspack to 1.4.0-beta.1

packages/document/docs/en/guide/more/faq.mdx, packages/document/docs/zh/guide/more/faq.mdx, packages/rspack-plugin/src/plugin.ts
chore(core): add concatenateModules info for rsppedy
=> chore(core): add concatenateModules info for rsppedy

packages/utils/src/logger.ts
=> chore: the logger style

packages/document/docs/en/guide/usage/bundle-size.mdx, packages/document/docs/zh/guide/usage/bundle-size.mdx
docs: tile graph documentation
=> docs: tile graph documentation

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
* feature: support the treemap graph. by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/1136
* docs: tile graph documentation by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/1139
* Release 1.1.4 by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/1128
* chore(deps): update all patch dependencies by @renovate in https://github.com/web-infra-dev/rsdoctor/pull/1132
* chore(deps): update dependency @lynx-js/react to ^0.110.0 by @renovate in https://github.com/web-infra-dev/rsdoctor/pull/1133
* chore(deps): update dependency @modelcontextprotocol/sdk to v1.13.0 by @renovate in https://github.com/web-infra-dev/rsdoctor/pull/1134
* chore: the logger style by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/1129
* optimize: decrese the client size …
=> release 1.1.5

e2e/cases/doctor-rspack/linter-rule-render.test.ts
chore: rm the error e2e test currently
=> chore: rm the error e2e test currently

packages/components/src/components/Charts/TreeMap.tsx, packages/components/src/components/Overall/help-center.tsx, packages/components/src/pages/BundleSize/components/cards.tsx, packages/components/src/pages/BundleSize/components/search-modal.tsx
=> fix: add some ui key

examples/rspack-banner-minimal/rspack.config.js, packages/utils/src/common/global-config.ts, pnpm-lock.yaml
fix: catch ci parse error
#1137
=> fix: catch ci parse error

e2e/cases/doctor-rspack/plugin.test.ts
fix: fix ci error
Because module is dynamic changes.
=> fix: fix ci error

packages/components/src/components/Loader/executions.tsx
fix: loader detail time error
closes: #1155
=> fix: loader detail time error

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
* fix: update @rspack/core to 1.4.3 and fix types by @chenjiahan in https://github.com/web-infra-dev/rsdoctor/pull/1158
* fix: open require error by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/1162
* release v1.1.7 by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/1156
**Full Changelog**: https://github.com/web-infra-dev/rsdoctor/compare/v1.1.7...v1.1.8
=> release v1.1.8

biome.json, examples/webpack-minimal/src/style.css, package.json, packages/components/src/utils/worker/utils.ts, packages/core/src/build-utils/build/utils/parseBundle.ts, pnpm-lock.yaml
update biome v2 
And fixed several lint issues
=> chroe: update biome v2

packages/document/package.json, pnpm-lock.yaml
chore: bump @rstack-dev/doc-ui
=> chore: bump @rstack-dev/doc-ui

packages/core/src/build-utils/build/utils/loader.ts, packages/core/tests/plugins/loader-path.test.ts
fix: loader path validation issue on Windows
#968
#1111
=> fix: loader path validation issue on Windows

packages/components/src/pages/BundleSize/components/cards.tsx
- Replace array mapping with direct component rendering
- Use selectedTitle state instead of index to prevent render inconsistency
- Optimize onChange event handling for smoother user experience
ref #1190
=> fix: resolve flickering issue in AssetCardContainer component

packages/components/src/components/Charts/TreeMap.tsx, packages/components/src/pages/BundleSize/components/index.tsx
=> optimize: add treemap info

.github/workflows/release.yml, .github/workflows/test-ubuntu.yml, .github/workflows/test-windows.yml, packages/ai/package.json, packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json, pnpm-lock.yaml, scripts/test-helper/package.json
=> release v1.1.11

packages/core/src/inner-plugins/plugins/sourcemapTool.ts
chore: change logger.error to debug in sourcemapTools
=> chore: change logger.error to debug in sourcemapTools

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
- **Concatenated Module Size Analysis:** Added the ability to analyze the size of **concatenated modules**, helping developers more accurately identify the actual build size after Tree Shaking.
- **Bundle Size Analysis with Gzip Support:** Bundle size analysis now displays the size after gzip compression, making it easier for developers to understand the real size of production assets.
- **Enhanced Treemap Visualization:** Introduced and improved the Treemap (rectangle tree map) feature, allowing developers to gain more intuitive insights into bundle composition and resource distribution.
* feat: sport the concatenated module size compute by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/1159
* feat: support the gzip in bundle analysis by @easy1090 in …
=> Release v1.2.0

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
* fix: treemap can be expanded after collapsed by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/1232
* docs: add quick install buttons for mcp by @charpeni in https://github.com/web-infra-dev/rsdoctor/pull/1231
* Release v1.2.0 by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/1228
* chore: change components config by @easy1090 in https://github.com/web-infra-dev/rsdoctor/pull/1233
**Full Changelog**: https://github.com/web-infra-dev/rsdoctor/compare/v1.2.0...v1.2.1
=> release v1.2.1

packages/components/src/components/Card/size.module.scss, packages/components/src/components/Charts/TreeMap.tsx, packages/components/src/components/Overall/bundle.module.scss
=> fix: echarts-react-import

.github/workflows/test-ubuntu.yml, .github/workflows/test-windows.yml
chore: add release branch workflow
=> chore: add release branch workflow

packages/cli/package.json, packages/cli/src/commands/analyze.ts, packages/cli/src/commands/stats-analyze.ts, packages/cli/src/constants.ts, packages/cli/src/index.ts, pnpm-lock.yaml
feat: add stats-json analysis with @rsdoctor/cli
Add cli command `stats-analyze --profile stats.json` to support bundle analysis to stats.json
=> feat: add stats-json analysis with @rsdoctor/cli

packages/cli/package.json, packages/core/package.json, packages/graph/package.json, packages/sdk/package.json, packages/webpack-plugin/package.json, pnpm-lock.yaml
Clean up package.json files by removing unused dependencies to reduce install size and maintenance overhead.
Found by [Knip](https://knip.dev/) (Some of the results in the screenshots are misjudgments):
=> chore: remove unused dependencies across packages

packages/core/modern.config.ts
remove unused modern config files
=> chore(build): remove unused modern config files

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
* fix(types): relieve original import path by @Gehbt in https://github.com/web-infra-dev/rsdoctor/pull/1260
* fix: Turn off checkModules filter by @yifancong in https://github.com/web-infra-dev/rsdoctor/pull/1263
* fix: the sourcemap tool sourceMapFile problem by @yifancong in https://github.com/web-infra-dev/rsdoctor/pull/1264
* docs: quick start page add Rslib by @EAGzzyCSL in https://github.com/web-infra-dev/rsdoctor/pull/1257
* chore: change tile to treemap by @yifancong in https://github.com/web-infra-dev/rsdoctor/pull/1249
* chore: remove unused dependencies across packages by @chenjiahan in https://github.com/web-infra-dev/rsdoctor/pull/1252
* chore(build): remove unused modern config files by @Timeless0911 in https://github.com/web-infra-dev/rsdoctor/pull/1255
* Release version …
=> release: v1.2.3

README.md, README.zh-CN.md, packages/document/docs/en/blog/release/release-note-1_0.mdx, packages/document/docs/en/guide/start/intro.mdx, packages/document/docs/zh/blog/release/release-note-1_0.mdx, packages/document/docs/zh/guide/start/intro.mdx
Noticed the link to Rslib wasn't working, updated it to the expected one.
=> docs: fix rslib link

packages/components/src/pages/Resources/BundleDiff/DiffContainer/modules.tsx, pnpm-lock.yaml
fix: diff page error
When the current data is undefined, the page will report an error, and the error will be repaired.
=> fix: diff page error

packages/components/src/pages/Uploader/index.tsx, packages/components/src/pages/Uploader/utils.ts, packages/components/src/utils/stats.ts, pnpm-lock.yaml
The upload and analysis capability for rspack's stats.json is problematic and needs to be fixed.
After the fix, users should be able to directly upload rsdoctor's manifest.json and rspack's stats.json on the rsdoctor website for instant analysis.
=> fix: uploader and analysis rspack stats.json

e2e/cases/doctor-rspack/uploader.test.ts, packages/components/src/pages/Uploader/index.tsx, packages/components/src/pages/Uploader/utils.ts, packages/document/package.json
1. chore: add executing build.sh command.
2. optimize the info in playground page.
3. optimize the uploader.test.ts.
=> chore: add build.sh command

packages/cli/package.json, packages/client/package.json, packages/components/package.json, packages/core/package.json, packages/document/package.json, packages/graph/package.json, packages/rspack-plugin/package.json, packages/sdk/package.json, packages/types/package.json, packages/utils/package.json, packages/webpack-plugin/package.json
* **Rsdoctor Playground**
* Support to upload Rspack’s stats.json and Rsdoctor‘s data online for analysis.[Playground](https://rsdoctor.rs/guide/start/playground)
https://github.com/user-attachments/assets/f4078afa-b8ca-4b22-a081-a1acbe4dc986
* **Support the Brief JSON format, allowing rsdoctor data to be exported as a JSON file for further analysis**
* This improves the ability to store and share rsdoctor data in CI environments.[Docs](https://rsdoctor.rs/config/options/output#options)
* **Rsdoctor refactored as dual packages.**
* feat: the config options changes by @yifancong in https://github.com/web-infra-dev/rsdoctor/pull/1270
* feat: support brief mode to generate json datas by @yifancong in https://github.com/web-infra-dev/rsdoctor/pull/1285
* feat: support upload and online …
=> release 1.3.0

packages/core/package.json, pnpm-lock.yaml
fix: the problem lacking enhanced-resolve
#1331
=> fix: the problem lacking enhanced-resolve
