- .changeset/nervous-ducks-judge.md
- packages/core/package.json
- packages/graph/package.json
- packages/sdk/package.json
- packages/utils/package.json
- pnpm-lock.yaml
Fix: lack the @rsdoctor/types packages 
#73
> fix: lack the rsdoctor types packages

- packages/client/package.json
- packages/components/src/components/Card/size.tsx
- packages/components/src/components/Card/statistic.tsx
- packages/components/src/pages/BundleSize/components/cards.tsx
- packages/components/src/pages/BundleSize/components/index.tsx
optimize bundle page cards UI
#81
> optimize(client): optimize bundle page cards

- .changeset/stale-tools-bow.md
- e2e/package.json
- examples/rsbuild-minimal/package.json
- examples/rsbuild-minimal/rsbuild.config.ts
- examples/rsbuild-minimal/src/App.tsx
- examples/rsbuild-minimal/src/semver.ts
- examples/rsbuild-minimal/src/semver7.ts
- examples/rspack-minimal/package.json
- examples/rspack-minimal/rspack.config.js
- packages/client/rsbuild.config.ts
- packages/components/src/components/Alert/package-relation.tsx
- packages/components/src/components/CodeViewer/hightlight.tsx
- packages/components/src/pages/BundleSize/components/asset.tsx
- packages/core/package.json
- packages/core/src/build-utils/build/module-graph/webpack/transform.ts
- packages/core/src/inner-plugins/plugins/bundle.ts
- packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
- packages/core/src/inner-plugins/plugins/index.ts
- packages/core/src/inner-plugins/plugins/rules.ts
- packages/core/src/rules/rules/loader-performance-optimization/index.ts
- packages/rspack-plugin/package.json
- packages/rspack-plugin/src/plugin.ts
- packages/test-helper/package.json
- packages/types/package.json
- packages/types/src/plugin/baseStats.ts
- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/src/plugin.ts
- pnpm-lock.yaml
1.  rspack mode add bundle analysis by rspack's hooks
2. rspack mode add rules scan
#95 
#96
> feat(bundle): rspack mode add bundle analysis by rspack's hooks and add rules scan.

- document/docs/en/guide/start/quick-start.mdx
- document/docs/zh/guide/start/quick-start.mdx
Improve quick start guide:
- fix incorrect sample code for Rsbuild.
- add example for `RSDOCTOR=true npm run build`.
- fix some small mistakes.
> docs: improve quick start guide

- cspell.json
- document/package.json
- document/theme/index.tsx
- pnpm-lock.yaml
Integrate rsfamily nav icon.
https://github.com/rspack-contrib/rsfamily-nav-icon
> docs: integrate rsfamily nav icon

- .changeset/tough-pumpkins-cry.md
- e2e/cases/doctor-webpack/fixtures/loaders/serialize-resource-query-to-comment.js
- e2e/cases/doctor-webpack/loaders/query.test.ts
- e2e/cases/doctor-webpack/loaders/resourceQuery.test.ts
- packages/core/src/build-utils/build/utils/loader.ts
- packages/core/tests/build/utils/loader/createLoaderContextTrap.test.ts
There are some problems in the implementation of two places.
1. in loader `this.query` hits `this.resourceQuery`
2. when `rule.use` is a function, rsdoctor cannot handle correctly
closes #155
> fix(core): proxy-loader behavior is not correct when query is string

- document/src/components/RuleIndex.module.scss
[Rules page](https://rsdoctor.dev/guide/more/rules) documentation is not accessible on dark mode, updated css to make the page accessible on dark mode(PFA)
**Summary**
Before
After
> fix(docs): rules page dark mode

- .changeset/calm-horses-travel.md
- .changeset/friendly-years-occur.md
- .changeset/light-news-report.md
- .changeset/nine-cheetahs-happen.md
- .changeset/polite-lamps-itch.md
- .changeset/tough-pumpkins-cry.md
- packages/client/CHANGELOG.md
- packages/client/package.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/graph/CHANGELOG.md
- packages/graph/package.json
- packages/rspack-plugin/CHANGELOG.md
- packages/rspack-plugin/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
- packages/test-helper/CHANGELOG.md
- packages/test-helper/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
- packages/utils/CHANGELOG.md
- packages/utils/package.json
- packages/webpack-plugin/CHANGELOG.md
- packages/webpack-plugin/package.json
- feat: integrate rslog as the logger
- fix: rsdoctor types package change the dependency of @rspack/core
- fix(rspack):optimize the builtin:swc-loader matching calculation
- fix(proxy-loader): proxy-loader behavior is not correct when query is string
- reuse browser tab on OS X
- bundle overall support woff/woff2 files
> Release v0.1.1

- .changeset/clean-comics-double.md
- packages/graph/src/graph/package-graph/graph.ts
fix(graph): dependency has some error
错误原因：
- path 为 `node_modules/.pnpm/@rspack+plugin-react-refresh@0.5.1_react-refresh@0.14.0/node_modules/@rspack/plugin-react-refresh/client` 时，当下是没有 package.json 的，就会走到下面代码的 `PackageUtil.getPackageMetaFromModulePath(file);` 逻辑：
```code
readFile(join(current, 'package.json')) ||
PackageUtil.getPackageMetaFromModulePath(file);
```
但其实这时应该继续向上一层文件夹去继续递归查找 package.json, 如果没有 readFile 时，才应该使用 `PackageUtil.getPackageMetaFromModulePath(file);` 来获取 npm package 的 name & version。
closes: #136
> fix(graph): dependency has some error

- .changeset/eleven-tomatoes-taste.md
- packages/core/src/build-utils/build/chunks/generateTileGraph.ts
- packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
fix(core): no parsed/gziped size on 'Bundle Analyzer Graph' page error.
closes: #164
> fix(core): no parsed/gziped size on 'Bundle Analyzer Graph' page error.

- document/docs/en/index.md
- document/docs/zh/index.md
- document/package.json
- document/rspress.config.ts
- pnpm-lock.yaml
This PR adds Open Sans as the default font for Rspack website, uses https://github.com/rspack-contrib/rspress-plugin-font-open-sans.
The Node.js new website is using Open Sans and looks good. see http://nodejs.org/
> docs: use Open Sans as the default font

- .github/pr-labeler.yml
- .github/release.yml
- .github/workflows/pr-label.yaml
Add PR labeler to workflow (the same as Rspack/Rsbuild/Rsdoctor), this allows to:
- add label for PR
- generate CHANGELOG via GitHub release.
> chore(workflow): add PR labeler

- .github/workflows/test-ubuntu.yml
Run cases in Node 18, as Node 16 can not be setup correctly.
The same as https://github.com/web-infra-dev/rspress/pull/909
> chore(CI): run cases in Node 18

- .changeset/config.json
Disable changeset changelog, we now use GitHub releases to generate changelog.
same as https://github.com/web-infra-dev/rspress/pull/919
> chore(workflow): disable changeset changelog

- packages/core/src/rules/rules/ecma-version-check/index.ts
Make the ECMA check log more authentic, "is bigger than" is not appropriate here.
> fix: make ECMA check log more authentic

- packages/rspack-plugin/src/builtinLoaderPlugin.ts
fix(plugin): the error of analyzing the missing builtin loader when rspack uses dev mode
#192
> fix(plugin): the error of analyzing the missing builtin loader when rspack uses dev mode

- packages/core/package.json
fix(core): the types exports problem.
When moduleRsolution is node or classic, the @rsdoctor/core’s types has export problem.
closes: #306
> fix(core): the types exports problem

- packages/rspack-plugin/src/plugin.ts
fix: multi plugin rspack output path error, has two .rsdoctor dir.
> fix: multi plugin rspack output path error

- packages/core/src/inner-plugins/plugins/base.ts
- packages/core/src/types/plugin.ts
- packages/rspack-plugin/src/plugin.ts
- packages/webpack-plugin/src/plugin.ts
fix: rule config types. fix the rule's config types to support for user to set the rule config:
```js
new RsdoctorWebpackPlugin({
linter: {
level: "Error",
extends: [],
rules: {
"default-import-check": "off",
"duplicate-package": [
"Error",
{
checkVersion: "minor",
ignore: ["chalk", "@bable/runtime"],
},
],
},
},
}),
```
[#311](https://github.com/web-infra-dev/rsdoctor/issues/311)
> fix(type): the rule's config types to support for user to set the rule config:

- .changeset/popular-hotels-bow.md
- packages/rspack-plugin/src/plugin.ts
fix(plugin): the BuiltinLoaderPlugin should skipped when close 'loader' in features
> fix(plugin): the BuiltinLoaderPlugin should skipped when close 'loader' in features

- packages/rspack-plugin/src/plugin.ts
The `compiler.compilation` api will be removed in Rspack `v0.7`. And we can get `stats` from the `compiler.hooks.done` callback parameter, not from the `compiler.compilation` api.
https://www.rspack.dev/api/plugin-api/compiler-hooks#done
https://github.com/web-infra-dev/rspack/pull/6448
> fix: remove use of rspack compiler.compilation api

- CONTRIBUTING.md
When I read  CONTRIBUTING.md, I found the e2e command has some error
In before CONTRIBUTING.md
In fact, the current command to run e2e is
None!
> docs(CONTRIBUTING.md): fix error description (e2e command)

- packages/core/package.json
- packages/core/src/inner-plugins/plugins/bundleTagPlugin.ts
- packages/core/src/inner-plugins/plugins/index.ts
- packages/core/src/inner-plugins/utils/config.ts
- packages/core/src/types/plugin.ts
- packages/rspack-plugin/package.json
- packages/rspack-plugin/src/plugin.ts
- packages/webpack-plugin/src/plugin.ts
- pnpm-lock.yaml
When BannerPlugin is used in the rspack project to add templates code to the assets, it will cause Rsdoctor's Bundle parsing to fail. In summary, Rsdoctor bundle analysis is required to support Banner Plugin.
```js
// rspack.config.js
plugins: [
new rspack.BannerPlugin({
test: /\.js/,
banner,
raw: true,
}),
]
```
1. Plugins that detect Compiler options have plug-in name === "BannerPlugin';
2. The second is to open it manually:
```ts
New RsdoctorRspackPlugin (
Supports: {
Banner: true
}
)
```
When InternalBannerPlugin is turned on, do not turn on Rsdoctor in the online template.
#345
> feat: support for  banner plugin.

- packages/rspack-plugin/src/plugin.ts
- packages/webpack-plugin/src/plugin.ts
I think the current way of determining whether to use webpack or rspack is not compatible with most scenarios. For example, in my scenario, I build the project through `@rspack/core`, but in the plugin, I use `@rsdoctor/webpack-plugin`.
Another note is that in this case, a compatible version of webpack in rspack will be used by default. For example, in `@rspack/core@0.7.0`, webpackVersion is "5.75.0". When I saw "5.75.0" on rsdoctor, I was very confused.
> chore: Modified the method of querying the current config

- packages/graph/src/graph/package-graph/graph.ts
fix(graph): this module which don't in any chunk no need to be counted
closes:  #387
> fix(graph): this module which don't in any chunk no need to be counted

- packages/graph/src/graph/package-graph/package.ts
perf: optimize the package graph algorithm.
In some repositories, a large amount of time is spent on the createPackageGraph function. It is because the path.relative api. So optimize the algorithm of `contain` function. After optimization, the createPackageGraph function has a 75% improvement in time efficiency.
Before：
After:
closes: #414
> perf: optimize the package graph algorithm

- packages/sdk/src/sdk/server/apis/renderer.ts
- packages/sdk/src/sdk/server/index.ts
fix(server): when no path,the client get error on '/' path.
When the user opens the page without a path path, but only the host and port point to the root path of the server, the page will be "GET ERROR Kawa, and this mr is to fix this problem. |
> fix(server): the client page get error on '/' path

- .changeset/long-seahorses-leave.md
- packages/sdk/src/sdk/sdk/core.ts
- packages/sdk/src/sdk/utils/upload.ts
- packages/utils/src/build/file/sharding.ts
- packages/utils/src/build/json.ts
- packages/utils/tests/__snapshots__/json.test.ts.snap
- packages/utils/tests/json.test.ts
- pnpm-lock.yaml
refactor the stream reading logic to divide segments for reading in order to prevent buffer error: invalid string length.
#167
> refactor: the stream logic of reading the json data.

- packages/document/docs/zh/guide/start/quick-start-shared.mdx
The wording of plugin used in rsbuild should be `RsdoctorRspackPlugin`, but get `RsdoctorWebpackPlugin` in zh doc now.
> docs: fix wording of plugin used in rsbuild

- packages/sdk/package.json
- packages/sdk/src/sdk/server/apis/project.ts
- packages/sdk/src/sdk/server/index.ts
- packages/sdk/src/sdk/server/utils.ts
- packages/sdk/tests/server/apis/project.test.ts
- pnpm-lock.yaml
The ip package through 2.0.1 for Node.js might allow SSRF because some IP addresses, so need upgrade.
https://github.com/advisories/GHSA-2p57-rm9w-gvfp
> fix: change ip to resolve the ip's SSRF risk

- packages/sdk/src/sdk/utils/openBrowser.ts
Include `win32` as part of platforms that will not use `open` package
move `open` package related code within `sdk/src/sdk/utils/openBrowser.ts` to `else` block
Issue: https://github.com/web-infra-dev/rsdoctor/issues/446
closed issue that inspired the change: https://github.com/web-infra-dev/rsdoctor/issues/159
> fix(sdk): HMR opens a new tab instead of updating the exsiting tab

- .github/renovate.json5
- packages/rspack-plugin/package.json
- packages/types/package.json
- fix: support rspack 1.x-beta.
- renovate: add ignore npm dependencies.
> chore: support rspack 1.x-beta

- examples/rsbuild-minimal/rsbuild.config.ts
- packages/core/src/inner-plugins/utils/config.ts
- packages/core/src/types/plugin.ts
- packages/rspack-plugin/src/plugin.ts
- packages/sdk/src/sdk/sdk/types.ts
- packages/sdk/src/sdk/sdk/webpack.ts
- packages/sdk/src/sdk/server/index.ts
- packages/types/src/sdk/instance.ts
- packages/webpack-plugin/src/plugin.ts
- feat(plugin): add pringLog options to control the terminal log outputs.
- refactor: the options.config object type.
#427
> feat(plugin): add pringLog options to control the terminal log outputs

- packages/components/src/components/CodeViewer/viewer.tsx
- packages/components/src/components/Loader/executions.tsx
- packages/components/src/pages/BundleSize/components/asset.tsx
- packages/components/src/pages/BundleSize/components/index.tsx
- packages/core/src/inner-plugins/utils/config.ts
- packages/core/src/types/plugin.ts
- packages/rspack-plugin/src/plugin.ts
- packages/sdk/src/sdk/sdk/webpack.ts
- packages/types/src/sdk/instance.ts
- packages/webpack-plugin/src/plugin.ts
Optimize the brief page：
1. optimize the editor when there no codes to show.
2. add open browser on brief mode.
3. support the `mode: lite`.
4. optimize the page of loader analysis
> [optimize]: the brief page

- packages/core/src/inner-plugins/plugins/progress.ts
Minor fix to innerprogress plugin that prevents whole compilation if sendAPIDataToClient throws.
closes https://github.com/web-infra-dev/rsdoctor/issues/481
> fix(progress): do not abort compilation when emit fails

- e2e/cases/doctor-rspack/brief.test.ts
- e2e/package.json
- e2e/playwright.config.ts
- packages/components/src/components/BundleDiff/DiffServerAPIProvider/index.tsx
- packages/core/src/inner-plugins/utils/config.ts
- packages/core/src/types/plugin.ts
- packages/rspack-plugin/src/plugin.ts
- packages/sdk/src/sdk/sdk/core.ts
- packages/sdk/src/sdk/sdk/webpack.ts
- packages/types/src/sdk/instance.ts
- packages/webpack-plugin/src/plugin.ts
feature: add brief configs
1. add outputDir options; closes: #474
2. add brief configs
brief: {
reportHtmlName?: string | undefined;
writeDataJson: boolean;
}
- reportHtmlName: control the brief html report name, default is 'rsdoctor-report.html'
- writeDataJson： brief mode will not generate the .rsdoctor data by default, you can use `writeDataJson: true`, to also generate the .rsdoctor json data.
3. add brief mode e2e tests.
closes: #474
> feature: add brief configs

- packages/core/src/build-utils/build/utils/loader.ts
I have code like this that fails when adding rsdoctor
```
rules: [
enableThing && new Plugin()
]
```
error message:
```
TypeError: Cannot use 'in' operator to search for 'rules' in false
at /Users/nick.bolles/Code/app/node_modules/@rsdoctor/core/dist/build-utils/build/utils/loader.js:145:17
at Array.map (<anonymous>)
at Object.mapEachRules (/Users/nick.bolles/Code/app/node_modules/@rsdoctor/core/dist/build-utils/build/utils/loader.js:92:16)
at interceptLoader (/Users/nick.bolles/Code/app/node_modules/@rsdoctor/core/dist/inner-plugins/utils/loader.js:110:29)
at InternalLoaderPlugin.getInterceptRules (/Users/nick.bolles/Code/app/node_modules/@rsdoctor/core/dist/inner-plugins/plugins/loader.js:147:45)
at InternalLoaderPlugin.afterPlugins …
```
> Filter out falsey rules

- packages/core/package.json
- packages/core/src/inner-plugins/plugins/bundleTagPlugin.ts
- packages/types/src/plugin/baseCompiler.ts
- pnpm-lock.yaml
Remove `webpack-sources` to reduce dependencies, both Rspack and webpack support `compiler.webpack.sources`.
> perf(deps): remove `webpack-sources` to reduce dependencies

- packages/document/theme/index.css
> docs: no need to override sidebar width

- packages/components/src/pages/BundleSize/components/asset.tsx
- Add some button's popover.
- Add directory's Source size Tag
> optimize(client): bundle size page add some infos

- packages/webpack-plugin/src/plugin.ts
Multi webpack plugin setSDK error: 
When in multiplugin, there will be more than one sdk, and getsDK will be based on the constructor. Name to match to get sdk, so you can cancel the judgment condition here.
> fix(plugin): multi webpack plugin setSDK error

- packages/cli/package.json
- packages/cli/src/commands/analyze.ts
- packages/cli/src/commands/bundle-diff.ts
- packages/cli/src/index.ts
- pnpm-lock.yaml
> No dependencies.
> 14 times smaller and 2 times faster than chalk.
If the maintainers agree with the migration then I will migrate other packages too
https://github.com/vercel/next.js/pull/70984
https://e18e.dev/blog/august-contributions-showcase.html#picocolors
> Chalk to picocolors migration

- e2e/cases/doctor-webpack/loaders/proxy.test.ts
- packages/cli/src/commands/analyze.ts
- packages/cli/src/commands/bundle-diff.ts
- packages/core/src/inner-plugins/plugins/base.ts
- packages/core/src/inner-plugins/utils/plugin.ts
- packages/core/src/inner-plugins/utils/sdk.ts
- packages/core/src/types/plugin.ts
- packages/rspack-plugin/src/plugin.ts
- packages/sdk/src/sdk/multiple/controller.ts
- packages/sdk/src/sdk/multiple/server.ts
- packages/sdk/src/sdk/multiple/slave.ts
- packages/sdk/src/sdk/sdk/index.ts
- packages/sdk/tests/utils.ts
- packages/webpack-plugin/src/plugin.ts
- packages/webpack-plugin/src/plugins/resolver.ts
> chore: change the typo words

- packages/components/src/pages/BundleSize/components/index.tsx
- The Tile Graph page should link to English documentation.
- Improve the tip.
> fix: should link to English documentation

- e2e/package.json
- examples/modern-minimal/package.json
- examples/multiple-minimal/package.json
- examples/rsbuild-minimal/package.json
- examples/rspack-banner-minimal/package.json
- examples/rspack-minimal/package.json
- packages/client/package.json
- packages/client/rsbuild.config.ts
- packages/core/package.json
- packages/core/src/inner-plugins/utils/config.ts
- packages/document/package.json
- packages/rspack-plugin/package.json
- packages/sdk/src/sdk/sdk/index.ts
- packages/types/package.json
- packages/webpack-plugin/package.json
- pnpm-lock.yaml
- scripts/test-helper/package.json
- Bump all Rsbuild related packages from v0.7 to v1.1.
- Bump all Rspack related packages from v1.0 to v1.1.
- Fix the `scriptSrcs` RegExp to allow it match `<script defer src="*">`
> chore(deps): bump Rspack and Rsbuild to v1.1

- packages/client/src/common/styles/base.scss
Eliminate a Sass deprecation warning:
See: https://sass-lang.com/documentation/breaking-changes/import/
> fix(client): eliminate Sass deprecation warning

- packages/core/src/build-utils/common/webpack/compatible.ts
fix(rspack-plugin): rspack moduleGrpah js api don't have getResolvedModule
> fix(rspack-plugin): rspack moduleGrpah js api don't have getResolvedModule

- .changeset/strong-games-beam.md
- e2e/cases/doctor-webpack/plugins/multi-plugin-brief.test.ts
- e2e/cases/doctor-webpack/test-utils.ts
- e2e/playwright.config.ts
- packages/rspack-plugin/src/multiple.ts
- packages/sdk/src/sdk/multiple/controller.ts
- packages/sdk/src/sdk/multiple/slave.ts
- packages/sdk/src/sdk/sdk/index.ts
- packages/webpack-plugin/src/multiple.ts
**Fix the error when options is reportCodeType: { noCode: true } and use the multi-plugin.**
Enhancements to `rsdoctor` plugins and configurations:
* [`e2e/cases/doctor-webpack/plugins/multi-plugin-brief.test.ts`](diffhunk://#diff-809b4d6f773c60070ed657032225edd792c05a9b7ec1208131d695913a9420b9R1-R56): Added a new test case for the `rsdoctor` webpack plugin with brief mode options.
* [`e2e/cases/doctor-webpack/test-utils.ts`](diffhunk://#diff-442d56496c75c775697696fe2d07a0f69a3d9315e8a36b3411d358502fcf0b20R41-R71): Introduced a new `createRsdoctorMultiPlugin` function to create instances of `RsdoctorWebpackMultiplePlugin` with enhanced options.
* [`packages/sdk/src/sdk/multiple/slave.ts`](diffhunk://#diff-e1c8e64efeefd306322e4a39175d5e8c922b64759528cc89d2ba2811f705c6ccR19): Updated the …
> fix(multi-plugin): fix multi-plugin options error

- packages/graph/package.json
- packages/sdk/package.json
- pnpm-lock.yaml
The package `@rsdoctor/graph` currently depends on a vulnerable version of `socket.io`.
```bash
cookie  <0.7.0
cookie accepts cookie name, path, and domain with out of bounds characters - https://github.com/advisories/GHSA-pxg6-pf52-xh8x
No fix available
node_modules/engine.io/node_modules/cookie
engine.io  1.8.0 - 6.6.1
Depends on vulnerable versions of cookie
node_modules/engine.io
socket.io  1.6.0 - 4.7.5
Depends on vulnerable versions of engine.io
node_modules/socket.io
@rsdoctor/graph  *
Depends on vulnerable versions of socket.io
node_modules/@rsdoctor/graph
@rsdoctor/core  *
Depends on vulnerable versions of @rsdoctor/graph
Depends on vulnerable versions of @rsdoctor/sdk
node_modules/@rsdoctor/core
@rsdoctor/rspack-plugin  *
Depends on vulnerable versions of @rsdoctor/core
Depends …
```
> chore(deps): update socket.io

- packages/core/src/build-utils/build/chunks/generateTileGraph.ts
- packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
fix: tile graph with reportDir
> fix: tile graph with reportDir

- packages/client/rsbuild.config.ts
- packages/components/src/pages/TreeShaking/table.tsx
- packages/components/src/pages/TreeShaking/utils.tsx
- packages/graph/package.json
- packages/graph/src/graph/module-graph/module.ts
- packages/graph/src/graph/module-graph/utils.ts
- packages/graph/src/graph/package-graph/graph.ts
- packages/utils/package.json
- packages/utils/src/common/index.ts
- packages/utils/src/common/lodash.ts
- packages/utils/src/common/package.ts
- packages/utils/src/error/error.ts
- packages/utils/src/rule-utils/document/document.ts
- packages/utils/src/rule-utils/parser/asserts.ts
- pnpm-lock.yaml
perf: reduce the bundle size of client
reduce lodash package, client bundle size from: 2.77 MB -> 2.75 MB
> perf: reduce the bundle size of client

- .github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
- .github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
- .github/workflows/pr-label.yaml
1. Since the `pr-labeler` workflow adds labels to pull requests, it needs the `pull-requests: write` permission.
2. The GitHub issue types work well and we can remove the issue label to reduce duplicated information.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#overview
> chore(CI): correct permissions for issue labeler

- packages/components/src/pages/Overall/index.module.scss
> fix(UI): failed to render `font-family-code` in macOS

- packages/components/src/components/Alerts/collapse.tsx
- packages/components/src/components/Overall/help-center.module.scss
- before:
- after:
- before:
- after:
> fix(UI): correct versions and title alignment

- packages/client/package.json
- packages/client/rsbuild.config.ts
- packages/sdk/package.json
- packages/sdk/src/sdk/server/index.ts
- pnpm-lock.yaml
[sirv](https://www.npmjs.com/package/sirv?activeTab=readme) is a very fast and lightweight alternative to [serve-static](https://www.npmjs.com/package/serve-static).
And Rsbuild already uses `sirv` to serve static assets: https://github.com/search?q=repo%3Aweb-infra-dev%2Frsbuild%20sirv&type=code
> Note that `sirv@3` requires Node 18, so I use the 2.x version for Rsdoctor.
https://www.npmjs.com/package/sirv
> perf: replace `serve-static` with `sirv`

- packages/core/src/build-utils/build/module-graph/webpack/transform.ts
Fix failed to call `getResolvedModule` in Rspack. Rspack does not support the `getResolvedModule` yet.
https://github.com/web-infra-dev/rsdoctor/pull/684
> fix: failed to call `getResolvedModule` in Rspack

- packages/components/src/pages/BundleSize/components/index.tsx
optimize: get the default asset when first load page
> optimize: get the default asset when first load page

- .gitignore
- packages/cli/tsconfig.json
- packages/client/tsconfig.json
- packages/components/src/components/BundleDiff/DiffContainer/modules.tsx
- packages/components/src/components/BundleDiff/DiffContainer/row.tsx
- packages/components/src/pages/BundleSize/components/asset.tsx
- packages/components/src/pages/Resources/BundleDiff/DiffContainer/modules.tsx
- packages/components/src/pages/Resources/BundleDiff/DiffContainer/row.tsx
- packages/components/tsconfig.json
- packages/core/tsconfig.json
- packages/document/tsconfig.json
- packages/graph/tsconfig.json
- packages/rspack-plugin/tsconfig.json
- packages/sdk/tsconfig.json
- packages/types/src/sdk/server/apis/index.ts
- packages/types/tsconfig.json
- packages/utils/src/common/data/index.ts
- packages/utils/tsconfig.json
- packages/webpack-plugin/tsconfig.json
- scripts/tsconfig/base.json
It's awful to have to compile every time the code is modified.
> chore: add composite and reference to tsconfig

- packages/utils/package.json
- packages/utils/src/rule-utils/parser/parser.ts
- pnpm-lock.yaml
Replace the deprecated `acorn-import-assertions` with `acorn-import-attributes`.
See: https://www.npmjs.com/package/acorn-import-assertions
> fix(deps): replace deprecated acorn-import-assertions

- packages/components/src/components/Overall/bundle.module.scss
> fix(UI): overall cards font overflow problem

- packages/components/src/components/Layout/header.scss
- packages/components/src/components/Layout/header.tsx
- packages/types/src/client.ts
When users click on the Rsdoctor logo, we can navigate to the home page because it fits the user's intuition.
> feat: logo as home link

- package.json
related to https://github.com/vitest-dev/vitest/issues/3143 and https://github.com/nodejs/node/issues/54735
> chore: prevent vitest segfault on github CI runner

- packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
- packages/core/src/inner-plugins/utils/config.ts
- packages/core/src/types/plugin.ts
- packages/rspack-plugin/src/multiple.ts
- packages/rspack-plugin/src/plugin.ts
- packages/sdk/src/sdk/sdk/core.ts
- packages/types/src/sdk/instance.ts
- packages/webpack-plugin/src/multiple.ts
- packages/webpack-plugin/src/plugin.ts
refactor: support compressJson option and refactor the reportDir & reportCodeType
This pull request introduces several changes to the `Rsdoctor` plugin configuration and usage, focusing on consolidating and restructuring the configuration options. The most important changes include moving the `reportDir` and `reportCodeType` options into a new `output` object, adding the `compressData` option, and updating the corresponding plugin classes and types to reflect these changes.
These changes improve the configuration structure and provide more flexibility in handling output options for the `Rsdoctor` plugin.
> refactor: support compressJson option and refactor the reportDir & reportCodeType

- e2e/cases/doctor-rspack/banner-plugin.test.ts
- e2e/cases/doctor-rspack/tag-plugin-without-banner.test.ts
- packages/core/src/inner-plugins/plugins/bundleTagPlugin.ts
- pnpm-lock.yaml
Change the InternalBundleTagPlugin to turn on the logic, when "supports. Banner' is true, or the BannerPlugin plug-in is used by default and supports. When banner' is not false, the InternalBundleTagPlugin analysis ability will be turned on.
————————————————————————————————————————————————————————————
更改 InternalBundleTagPlugin 开启逻辑，当 `supports.banner` 为 true，或默认使用了 BannerPlugin 插件且 `supports.banner` 不为 false 时，会开启 InternalBundleTagPlugin 分析能力。
> fix: banner plugin switch condition

- .github/workflows/test-ubuntu.yml
- e2e/README.md
- e2e/cases/doctor-rspack/brief.test.ts
- e2e/cases/doctor-rspack/linter-rule-render.test.ts
- e2e/package.json
- e2e/test-kit/launch.ts
- examples/multiple-minimal/package.json
- examples/rsbuild-minimal/package.json
- examples/webpack-minimal/package.json
- packages/client/package.json
- packages/components/package.json
- pnpm-lock.yaml
Fix the deprecated dependencies warning:
- `eslint` can be removed as Rsdoctor use Biome for linting.
- bump `playwright` to v1.44
- bump `@rsbuild/core` to v1.2
> chore: fix deprecated dependencies warning

- packages/core/src/build-utils/build/module-graph/webpack/transform.ts
- packages/core/src/build-utils/common/webpack/compatible.ts
Fix failed to call `module.getExportsType` method:
Rspack does not support `getExportsType` yet, so we need to add back some compatibility code.
The compatibility code is similar to this method:  https://github.com/web-infra-dev/rsdoctor/commit/417d63fe0c7faa4d9075de734c8db29a26aa78d9#diff-f56b842e05e9c881a3ecc025330e4dfbb62bbe887c46e27e63de815cff386684L77
> fix: failed to call `module.getExportsType` method

- packages/components/src/components/Loader/Analysis/style.module.scss
Fix invalid font family for loader analysis text, we can remove `font-family: 'Roboto'` and inherit the parent font family (which is `var(--font-family-code)`).
- before:
- after:
> fix(UI): invalid font family for loader analysis text

- packages/document/docs/en/guide/start/quick-start-shared.mdx
- packages/document/docs/zh/guide/start/quick-start-shared.mdx
Update "getting started" guide section for Rsbuild to align usage with the Rsbuild documentation.
resolve https://github.com/web-infra-dev/rsdoctor/issues/398
> docs: update "getting started" guide section for Rsbuild

- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test-ubuntu.yml
- .github/workflows/test-windows.yml
Add `npm install -g corepack@latest --force` before `corepack enable` to fix corepack key id mismatch issue.
> `--force` to prevent windows install error
https://github.com/nodejs/corepack/issues/612
> ci(corepack): fix corepack key id mismatch

- packages/rspack-plugin/tsconfig.json
Correct the dist types directory for `@rsdoctor/rspack-plugin`:
- before:
- after:
> fix(rspack-plugin): correct the dist types directory

- packages/client/package.json
- packages/client/rsbuild.config.ts
- packages/sdk/package.json
- packages/sdk/src/sdk/server/index.ts
- pnpm-lock.yaml
Switch from `static-serve` to `sirv`, and add `dev: true` to disable cache.
- resolve https://github.com/web-infra-dev/rsdoctor/issues/694
- https://github.com/web-infra-dev/rsdoctor/pull/691
- https://github.com/web-infra-dev/rsdoctor/pull/683
> fix: switch to sirv and disable cache

- e2e/cases/doctor-webpack/experiments.test.ts
- e2e/package.json
- packages/core/src/build-utils/build/utils/plugin.ts
- packages/core/src/inner-plugins/utils/plugin.ts
If the `experiments.backCompat: false' is set,the repo will have this problem:
```
TypeError: Cannot read properties of undefined (reading '_fakeHook')
at shouldInterceptPluginHook (/Users/d.kholstinin/projects/tramvai/node_modules/@rsdoctor/core/dist/build-utils/build/utils/plugin.js:28:12)
```
This pull request includes a small change to the `interceptPluginHook` function in the `packages/core/src/inner-plugins/utils/plugin.ts` file. The change adds a safe navigation operator to ensure that the `intercept` property is accessed safely.
* [`packages/core/src/inner-plugins/utils/plugin.ts`](diffhunk://#diff-023b84789a4a53582840c427fd946f3abe4eacda4e30a4637511dd5abfb28f02L43-R43): Modified the `interceptPluginHook` function to use the safe navigation operator when accessing the `intercept` …
> fix: expriments.backCompat problem

- packages/components/src/utils/socket.ts
- Problem
When hostname is url name, `url.toString()` will include the port, like: `http://urlHostName:port/`.
- Fix codes:
This pull request includes changes to the `packages/components/src/utils/socket.ts` file to enhance URL formatting and validation. The most important changes are the addition of an IPv4 pattern for hostname validation and the modification of the `formatURL` function to use this pattern.
> fix(sdk): the error of websocket

- packages/components/src/components/Loader/Analysis/files.tsx
- packages/utils/src/common/loader.ts
fix: summary loader consuming time of dirs.
1. Modify the time consumption calculation algorithm for Loaders in a specific folder:
After the change, the logic is to count the time consumption by loader. If the loader has overlapping time consumption, as shown in the situation below, it will only be counted once. However, since there will be overlapping time issues between different loaders, the total time consumption for different loaders will no longer be displayed.
Example for loader blocked:
| ---- |
--  |-----|
2. Modify the time consumption logic for a single file in the Rust loader of rspack:
Because the JS side loader operates in a single thread, it can directly exclude overlapping time consumption based on the PID, with overlapping time being blocking time. However, since the Rust …
> fix: summary loader consuming time of dirs

- pnpm-lock.yaml
Fix the broken pnpm-lock.yaml on the main branch: https://github.com/web-infra-dev/rsdoctor/actions/runs/13327415909/job/37223642538
Also run `pnpm dedupe` to reduce duplicated dependencies.
> chore: fix the broken pnpm-lock.yaml

- packages/components/src/components/Loader/Analysis/style.module.scss
- packages/utils/src/common/loader.ts
Fix the loader page ui problem：optimize the display of loader name.
- before
- after
> fix: optimize the display of loader name

- packages/components/src/components/Loader/Analysis/files.tsx
- packages/components/src/pages/BundleSize/components/asset.tsx
- packages/components/src/pages/BundleSize/components/index.tsx
- packages/core/src/rules/rules/duplicate-package/index.ts
Fix some UI problems:
1. Adjust the scroll area: the scrollable area can be adjusted from the entire modules box to only scroll for fileTree
2. Fix the display problem caused by fileTree searching for keywords
- before
- after
> Fix(ui): The file tree elements have problems with keyword searches.

- e2e/package.json
- examples/rspack-banner-minimal/package.json
- examples/rspack-layers-minimal/package.json
- examples/rspack-minimal/package.json
- packages/core/package.json
- packages/core/src/build-utils/build/utils/loader.ts
- packages/rspack-plugin/package.json
- packages/types/package.json
- pnpm-lock.yaml
- scripts/test-helper/package.json
This pull request includes multiple updates to various `package.json` files across different modules, mainly focusing on upgrading the `@rspack/core` dependency to version `^1.2.5`. Additionally, there is a minor code update in the `loader.ts` file to address a TypeScript error.
Dependency updates:
* [`e2e/package.json`](diffhunk://#diff-a02b008b50077ce0795c0dee89c3b663ead543e6d790874baece325aee7f1043L21-R21): Upgraded `@rspack/core` from `^1.2.3` to `^1.2.5`.
* [`examples/rspack-banner-minimal/package.json`](diffhunk://#diff-07797589814038deaa6f57075c57325e4630011edb35775e8b0224ce1ec5add9L22-R23): Upgraded `@rspack/cli` and `@rspack/core` from `^1.1.1` to `^1.2.5`.
* [`examples/rspack-layers-minimal/package.json`](diffhunk://#diff-880691427f799664e2fa5f6f2f026cac244cd0834e37b9f200b7f4e29e …
> chore: bump rspack to 1.2.5

- packages/document/docs/en/config/options/options.mdx
- packages/document/docs/zh/config/options/options.mdx
This pull request includes changes to the documentation files to introduce a new configuration option for enabling the Rspack native plugin. The changes add details about this new option in both the English and Chinese versions of the documentation.
Documentation updates:
* [`packages/document/docs/en/config/options/options.mdx`](diffhunk://#diff-1ed900ad28402e2526bc18d04eb8524c77658f9966f91760de11e90860151bc4R110-R130): Added a new section under `experiments` for the `enableNativePlugin` option, including its type, default value, description, and an example of how to configure it.
* [`packages/document/docs/zh/config/options/options.mdx`](diffhunk://#diff-b001fe80cc79d90e4be01c2d4e67bd5d9b3deb5bacb941c5ccab39f5bba14439R189-R209): Added a new section under `experiments` for the …
> docs: add experiments enableNativePlugin option

- packages/components/src/pages/BundleSize/components/index.tsx
| Before | After |
| - | - |
| <img width="523" alt="Screenshot 2025-03-04 at 3 22 47 PM" src="https://github.com/user-attachments/assets/e59ed9dd-8cba-4711-8b3a-9fe2e5abe34f" /> | <img width="516" alt="Screenshot 2025-03-04 at 3 30 02 PM" src="https://github.com/user-attachments/assets/9228b2bf-435d-4cc2-b0c5-ba1f73e1ac72" /> |
> fix(ui): add spacing between tile graph disabled and the link

- packages/components/src/pages/BundleSize/components/asset.tsx
| Before | After |
| - | - |
| <img width="271" alt="Screenshot 2025-03-04 at 2 08 39 PM" src="https://github.com/user-attachments/assets/42fb309c-2c25-4f1f-afb7-2fa8549c3424" /> | <img width="281" alt="Screenshot 2025-03-04 at 2 11 11 PM" src="https://github.com/user-attachments/assets/95ce69f0-40f2-4c7e-a05f-1564769b17fd" /> |
> fix(ui): add spacing before the modules count

- package.json
- packages/document/docs/en/config/options/options.mdx
- packages/document/docs/zh/config/options/options.mdx
This pull request includes multiple changes to the documentation for the `RsdoctorWebpackPlugin` and `RsdoctorRspackPlugin` in both English and Chinese. The most important changes include adding new configuration options, updating deprecated references, and improving the structure and clarity of the documentation.
* Added descriptions for new configuration options `brief`, `experiments`, `mode`, `output`, `port`, and `supports` in the English documentation.
* Introduced the `compressData` option to configure data compression in the English documentation.
* Added the `generateTileGraph` option to enable tile graph generation in the English documentation.
* Updated deprecated references to use the correct Chinese translations in the English documentation.
* Reorganized the Chinese …
> docs: optimize the options documents

- packages/components/src/pages/BundleSize/components/index.tsx
The previous tooltip had some typos and wasn't ideal as the max width ended up being too small to be readable.
| Before | After |
| - | - |
| <img width="271" alt="Screenshot 2025-03-04 at 12 12 39 PM" src="https://github.com/user-attachments/assets/6c9aec1b-5dd3-4fcf-8d81-3f401958c4c3" /> | <img width="385" alt="Screenshot 2025-03-04 at 1 54 11 PM" src="https://github.com/user-attachments/assets/13c4acdd-05fa-40fb-943f-5d5c93501b9b" /> |
| | <img width="400" alt="Screenshot 2025-03-04 at 1 54 19 PM" src="https://github.com/user-attachments/assets/20897586-5375-4f5f-afc4-f19600d957c0" /> |
> feat(ui): improve tree graph tooltip

- examples/webpack-minimal/webpack.config.ts
While reading through examples, I realized [`examples/webpack-minimal/webpack.config.ts`](https://github.com/web-infra-dev/rsdoctor/blob/main/examples/webpack-minimal/webpack.config.ts) was using multiple indentations that weren't matching with other files. Let's fix that with Prettier.
> chore(examples): fix the indentation used in `webpack-minimal`

- packages/core/src/build-utils/build/utils/parseBundle.ts
fix: parsing module failed in lynx projects
background.js will be compressed again, lead to the parse bundle error, console.log -> _.log
> fix: parsing module failed in lynx projects

- examples/rspress-minimal/package.json
- packages/document/package.json
- packages/document/rspress.config.ts
- packages/document/theme/index.tsx
- pnpm-lock.yaml
Update Rspress to 2.0.0-alpha.3 and handle some breaking changes.
https://github.com/web-infra-dev/rspress/releases/tag/v2.0.0-alpha.3
>  chore(deps): update Rspress to 2.0.0-alpha.3

- packages/core/src/inner-plugins/plugins/bundleTagPlugin.ts
- packages/document/docs/en/config/options/options.mdx
- packages/document/docs/en/guide/usage/bundle-size.mdx
- packages/document/docs/zh/config/options/options.mdx
- packages/document/docs/zh/guide/usage/bundle-size.mdx
Updating the messaging related to the `supports.banner` option to clarify that it is intended for debugging purposes only and should not be used in production. 
- before:
- after:
> fix: update `supports.banner` logs

- packages/cli/README.md
- packages/client/README.md
- packages/components/README.md
- packages/core/README.md
- packages/graph/README.md
- packages/rspack-plugin/README.md
- packages/sdk/README.md
- packages/types/README.md
- packages/utils/README.md
- packages/webpack-plugin/README.md
Clean up outdated features descriptions and usage examples in each pacakge's README.
Users should check https://rsdoctor.dev/ for the latest introduction and guides.
> docs: cleanup README files

- e2e/cases/doctor-webpack/fixtures2/a.js
- e2e/cases/doctor-webpack/fixtures2/b.js
- e2e/cases/doctor-webpack/fixtures2/index.less
- e2e/cases/doctor-webpack/fixtures2/loaders/comment.js
- e2e/cases/doctor-webpack/fixtures2/loaders/serialize-query-to-comment.js
- e2e/cases/doctor-webpack/fixtures2/loaders/serialize-resource-query-to-comment.js
- e2e/cases/doctor-webpack/fixtures2/port.js
- e2e/cases/doctor-webpack/plugins/loader-mini-css-extract.test.ts
- packages/core/src/inner-plugins/utils/loader.ts
- pnpm-lock.yaml
fix: the problem when use mini-css-extract-plugin loader
The mini-css-extract-plugin will initiate a childCompiler, within which the loader proxy logic will be executed again. This will result in the options[Loader.LoaderInternalPropertyName] of the loader proxy still being the proxy loader, causing errors in CSS and LESS compilation.
This pull request addresses an issue with the `interceptLoader` function in the `loader.ts` file, specifically related to how the `LoaderInternalPropertyName` is set for proxy-loader in the childCompiler of the mini-css-extract-plugin. The most important change involves conditionally setting the `LoaderInternalPropertyName` to prevent errors during the compilation of less files.
Improvements to error handling:
* …
> fix: the problem when use mini-css-extract-plugin loader

- packages/components/src/components/Loader/executions.tsx
Add side-by-side Checkbox in diffview.
**reason：**
The monaco DiffEditor has a default behavior that is auto SideBySide at break point width (default 900px). 
see: https://microsoft.github.io/monaco-editor/docs.html#interfaces/editor.IDiffEditorBaseOptions.html#renderSideBySideInlineBreakpoint
close: https://github.com/web-infra-dev/rsdoctor/issues/864
> feat: UI execution diff view add side-by-side check

- packages/core/src/build-utils/common/module-graph/transform.ts
- packages/core/tests/common/module-graph/__snapshots__/transform.test.ts.snap
- packages/graph/src/graph/module-graph/module.ts
- packages/types/src/plugin/baseStats.ts
- packages/types/src/sdk/module.ts
feat: module instance add issuerPath
This pull request introduces several changes to enhance the handling of issuer paths in the module graph. The most important changes include adding methods to manage issuer paths, updating interfaces to include issuer paths, and ensuring issuer paths are properly handled during the module graph transformation.
Enhancements to issuer path handling:
* [`packages/core/src/build-utils/common/module-graph/transform.ts`](diffhunk://#diff-683f99c6bbe04589b9793214c16144bcd527fd6e2b02022ea62d3869b2e48b8aR99-R102): Added logic to handle `issuerPath` in multiple places within the `getModuleGraphByStats` function. This includes adding issuer paths to modules and updating issuer identifiers. [[1]](diffhunk://#diff-683f99c6bbe04589b9793214c16144bcd527fd6e2b02022ea62d …
> feat: module instance add issuerPath

- packages/client/package.json
- packages/client/rsbuild.config.ts
- packages/components/modern.config.ts
- pnpm-lock.yaml
While developing the Client, I encountered an issue affecting the development experience - the development version code was being bundled and minified. This led to efficiency problems.
For example, I couldn't view component names through the React dev tools plugin, and it was difficult to locate target files.
**Here is my dev workflow：**
- Startup:
1. Launch an examples project, such as the `build:analysis` command for `rspress-minimal`
2. Sequentially start the start commands for `packages/client` and `packages/components`
- Development:
1. Local file changes trigger repackaging of the package
1. Wait for packaging to complete before refreshing the browser to see effects
1. `packages/components` uses `modernjs` for bundling, with sourcemap config added
1. `packages/client` uses `rsbuild` …
> core: Optimize Client Development Experience

- packages/core/src/build-utils/common/module-graph/transform.ts
- packages/core/tests/common/module-graph/__snapshots__/transform.test.ts.snap
- packages/core/tests/common/module-graph/transform.test.ts
- packages/graph/src/graph/module-graph/module.ts
- packages/types/src/plugin/baseStats.ts
- packages/types/src/sdk/module.ts
Adjust the issuerPath to only include module ids.
The same issuerPath type with rspack native plugin: https://github.com/web-infra-dev/rspack/pull/10007
> tweaks: adjust the issuerPath to only include module ids

- CONTRIBUTING.md
Some links in [`CONTRIBUTING.md`](https://github.com/charpeni/rsdoctor/blob/main/CONTRIBUTING.md) were redirecting to `rsbuild` instead of `rsdoctor`, probably artifacts from the repository creation.
Additionally, one link to `https://github.com/settings/emails` wasn't formatted correctly.
> docs: fix links in `CONTRIBUTING.md`

- packages/components/src/pages/BundleSize/components/asset.tsx
> fix: add spacing to bundled and source sizes

- README.md
The license badge led to rsbuild's license instead of rsdoctor's.
> docs: update license badge link

- packages/components/src/components/Alerts/overlay.tsx
> fix: improve `OverlayAlerts` spacing and add pluralization

- examples/multiple-minimal/package.json
- examples/rspack-banner-minimal/package.json
- examples/rspack-layers-minimal/package.json
- examples/rspack-minimal/package.json
- examples/webpack-minimal/package.json
- pnpm-lock.yaml
> chore: use `tsx` instead of  `tsm`

- packages/document/package.json
- packages/document/rspress.config.ts
- pnpm-lock.yaml
- scripts/dictionary.txt
https://v2.rspress.dev/plugin/official-plugins/llms#usage
[Rspack](https://rspack.dev)
Website:[rspack.dev](https://rspack.dev)
llms.txt: [rspack.dev/llms.txt](https://rspack.dev/llms.txt)
llms-full.txt: [rspack.dev/llms-full.txt](rspack.dev/llms-full.txt)
[Rsbuild](https://rsbuild.dev/)
Website:[rsbuild.dev](https://rsbuild.dev)
llms.txt: [rsbuild.dev/llms.txt](https://rsbuild.dev/llms.txt)
llms-full.txt: [rsbuild.dev/llms-full.txt](rsbuild.dev/llms-full.txt)
[Rslib](https://lib.rsbuild.dev)
Website:[lib.rsbuild.dev](https://lib.rsbuild.dev)
llms.txt: [lib.rsbuild.dev/llms.txt](https://lib.rsbuild.dev/llms.txt)
llms-full.txt: [lib.rsbuild.dev/llms-full.txt](lib.rsbuild.dev/llms-full.txt)
[Rsdoctor](https://rsdoctor.dev/)
Website:[rsdoctor.dev](https://rsdoctor.dev.dev)
llms.txt: …
> docs(llms): bump rspress to 2.0.0-beta.3 and ship llms.txt

- examples/rsbuild-minimal/rsbuild.config.ts
- packages/ai/src/server/server.ts
- packages/ai/src/server/socket.ts
- packages/ai/src/server/tools.ts
- packages/sdk/src/sdk/server/index.ts
- packages/utils/src/common/data/index.ts
- packages/utils/src/common/global-config.ts
- packages/utils/src/common/index.ts
feat: rsdoctor mcp get auto port
This pull request introduces functionality to manage and retrieve MCP server port information, along with several related enhancements and fixes. The changes include adding utilities for handling MCP configuration (`mcp.json`), updating server and socket logic to use these utilities, and improving error handling and data processing in other parts of the codebase.
* Added `writeMcpPort` and `getMcpConfigPath` utilities in `packages/utils/src/common/global-config.ts` to manage MCP port configuration in a `mcp.json` file. These utilities allow storing and retrieving port information for different builders.
* Updated `RsdoctorServer` in `packages/sdk/src/sdk/server/index.ts` to write the MCP port to `mcp.json` upon server initialization and log the …
> feat: rsdoctor mcp get auto port

- packages/rspack-plugin/package.json
- packages/rspack-plugin/src/multiple.ts
Mark `@rspack/core` as optional peer dependency to fix the "unmet peer dependency" warning with Rsbuild.
- see https://github.com/web-infra-dev/rsbuild/discussions/5192
> fix(rspack-plugin): mark @rspack/core as optional peer

- packages/ai/src/server/socket.ts
fix: the rsdoctor mcp-server change the builder property to compiler
#1082
> fix: the rsdoctor mcp-server change the builder property to compiler

- packages/document/i18n.json
- packages/document/package.json
- packages/document/theme/components/ToolStack.tsx
- pnpm-lock.yaml
- Update @rstack-dev/doc-ui to 1.10.0 to add Rstest to homepage.
- This update also includes some UI and text improvements.
Related: https://github.com/rspack-contrib/rstack-doc-ui/releases
> docs: add Rstest to homepage

- packages/document/docs/en/guide/start/cli.mdx
- packages/document/docs/zh/guide/start/cli.mdx
- packages/document/package.json
- packages/document/rspress.config.ts
- packages/document/theme/index.tsx
- pnpm-lock.yaml
docs(rspress): use @rspress/plugin-algolia for search and upgrade rspress version 2.0.0-beta.6
https://github.com/web-infra-dev/rspack/pull/10454
> docs(rspress): use @rspress/plugin-algolia for search and upgrade rspress version 2.0.0-beta.6

- packages/components/src/pages/BundleSize/components/asset.tsx
- packages/document/docs/en/guide/usage/bundle-size.mdx
- packages/document/docs/zh/guide/usage/bundle-size.mdx
This PR introduces improvements to the bundle size page by refactoring tag components for better modularity and readability. 
Added reusable components like `ConcatenatedTag`, `BundledSizeTag`, `TotalBundledSizeTag`, `SourceSizeTag`, and `TotalSourceSizeTag` to encapsulate tooltip.
> feat: add tooltips for bundle size tags

- packages/core/src/inner-plugins/utils/config.ts
- packages/core/tests/build/utils.ts
- packages/core/tests/build/utils/config.test.ts
- packages/core/tests/build/utils/parseBundle.test.ts
- packages/core/tests/tsconfig.json
tweaks(core): optimize the normalizeUserConfig and supply some tests. **No impact on users.**
This pull request refactors the `normalizeUserConfig` function and related utilities, introduces helper functions for default values, and adds comprehensive test coverage. It also includes minor updates to imports and configuration files.
* Refactored `normalizeUserConfig` in `packages/core/src/inner-plugins/utils/config.ts` by extracting default value logic into new helper functions: `getDefaultOutput`, `getDefaultSupports`, `normalizeFeatures`, and `normalizeLinter`. This improves readability and modularity. [[1]](diffhunk://#diff-0bc1a98d5cf2810e43077f2e07c17dced9b44cbbb6f1f19e517f4bdcfd222015L25-R57) [[2]](diffhunk://#diff-0bc1a98d5cf2810e43077f2e07c17dced9b44cbbb6f1f19e517f4bdcfd222015R67-R11 …
> tweaks(core): optimize the normalizeUserConfig and supply tests

- e2e/cases/doctor-rspack/plugin.test.ts
- packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
fix: rspack bundle analysis failed when open treeshaking
closes: #1153
> fix: rspack bundle analysis failed when open treeshaking

- examples/rspack-banner-minimal/package.json
- package.json
check-dependency-version 5.0.1 update command from v12 to v13 which will throw an error with excessArguments
> chore: correct check-dependency-version script

- e2e/cases/doctor-rspack/fixtures/index.js
- e2e/cases/doctor-rspack/fixtures/index.ts
- e2e/cases/doctor-rspack/sourcemap.test.ts
- packages/core/src/build-utils/common/chunks/assetsModules.ts
- packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
- packages/core/src/inner-plugins/plugins/sourcemapTool.ts
- packages/core/tests/plugins/sourcemapTool.test.ts
- packages/sdk/src/sdk/sdk/index.ts
- packages/utils/src/logger.ts
- fix: sourcemap parse tool
- e2e: add rspack & webpack e2e tests.
#1170
> fix: sourcemap parse tool

- packages/core/src/build-utils/build/utils/loader.ts
- packages/core/tests/plugins/loader-path.test.ts
- Added extensive tests for `isESMLoader` in `packages/core/tests/plugins/loader-path.test.ts` to validate handling of absolute paths, relative paths, package names, mixed path separators, edge cases, and loader objects.
- Changed `path` import to use `node:path` for better compatibility in `packages/core/src/build-utils/build/utils/loader.ts`.
- Replaced `_loaderName.startsWith('/')` with `path.isAbsolute(_loaderName)` for improved absolute path detection in `isESMLoader`.
> hotfix: normalization function problem

- .github/workflows/test-ubuntu.yml
- .github/workflows/test-windows.yml
- packages/core/src/inner-plugins/utils/config.ts
- packages/core/tests/build/utils/config.test.ts
hotfix: normallize config
This pull request introduces changes to workflow configurations and updates to the `normalizeReportType` function and its associated tests in the codebase. The most notable changes include extending workflow triggers to support `hotfix` branches and refining the logic for handling `reportCodeType` and `mode` in the `normalizeReportType` function, along with corresponding updates to test cases.
* [`packages/core/src/inner-plugins/utils/config.ts`](diffhunk://#diff-0bc1a98d5cf2810e43077f2e07c17dced9b44cbbb6f1f19e517f4bdcfd222015R218-R237): Refined logic to prioritize `reportCodeType.noCode` and adjusted handling of `mode:lite` to consistently return `SDK.ToDataType.NoSourceAndAssets`.
* `packages/core/tests/build/utils/config.test.ts`: 
- Updated existing test …
> hotfix: normallize config

- packages/components/src/components/Alerts/bundle-alert.tsx
- packages/components/src/components/Alerts/collapse.tsx
- Fix typo
- Add data sort by total size in Bundle Alerts -> Duplicate Packages
Why choose to directly increase the sorting of data, instead of adding a sort button. The reason is that under the current code organization structure, adding a sort button would have a significant impact on the code structure. Moreover, for the purpose of data presentation, it is only necessary to have sorted data packages to improve processing efficiency, and there is no need to switch to an unsorted state. Adding a sorting toggle function is not helpful.
close https://github.com/web-infra-dev/rsdoctor/issues/1145
> feat: fix typo and improve alert collapse sorting

- packages/ai/README.md
- packages/ai/README.zh-CN.md
- packages/document/docs/en/guide/start/mcp.mdx
- packages/document/docs/zh/guide/start/mcp.mdx
- packages/document/rspress.config.ts
A few things happened here:
- Added a `Add to Cursor` button to quickly add Rsdoctor MCP to Cursor without having to deal with the configuration file manually
- Noticed we had a section on the website for GitHub Copilot (VS Code), but not in the README. I synced it.
- Added an install button for VS Code too
> docs: add quick install buttons for mcp

- packages/types/src/sdk/module.ts
- packages/types/src/sdk/server/apis/index.ts
This package is building by tsc, but tsc does not change import paths.
@rsdoctor/types@1.2.2 in npm
`@rsdoctor/types/dist/sdk/module.d.ts`
`@rsdoctor/types/dist/sdk/server/apis/index.d.ts`
none
> fix(types): relieve original import path

- packages/core/src/inner-plugins/plugins/bundle.ts
fix: devtool module file template
When webpack's output.devtoolModuleFilenameTemplate is set to webpack://[namespace]/[resource-path], it is not possible to obtain the actual locations of the sources in the sourcemap. Therefore, rsdoctor will uniformly set it to '[absolute-resource-path]'.
> fix: devtool module file template

- packages/core/src/inner-plugins/plugins/ensureModulesChunkGraph.ts
- packages/types/src/plugin/baseStats.ts
perf: optimize the stats.toJson's time-consuming
> perf: optimize the stats.toJson's time-consuming

- package.json
- packages/core/src/inner-plugins/loaders/proxy.ts
- packages/core/src/inner-plugins/plugins/loader.ts
fix: proxy loader return undefined error
When use the loader/proxy.js esm module, the cssextractloader will report this error belowing, so need to change to loader/proxy.cjs.
But I'm not sure why using loader/proxy.js causes this problem.
> fix: proxy loader return undefined error

- packages/components/src/components/Alerts/collapse-cross-chunks.tsx
- packages/components/src/components/Alerts/collapse.tsx
In Bundle Alerts, we couldn't collapse a section because they were all collapsing instead of maintaining a unique state, which makes scrolling through all the data more difficult. Was it expected? I don't think so.
https://github.com/user-attachments/assets/926a293c-1e70-466f-bc8f-b42bcfd4d20e
https://github.com/user-attachments/assets/d3285ff0-bf25-47a4-ad0b-c4c338f58ef0
> fix: ensure unique collapsible key

- packages/cli/src/commands/analyze.ts
- packages/core/package.json
- packages/core/src/inner-plugins/utils/config.ts
- packages/core/src/inner-plugins/utils/index.ts
- packages/core/src/inner-plugins/utils/normalize-config.ts
- packages/core/src/types/plugin.ts
- packages/core/tests/build/utils/config.test.ts
- packages/rspack-plugin/src/multiple.ts
- packages/rspack-plugin/src/plugin.ts
- packages/sdk/src/sdk/sdk/core.ts
- packages/types/src/sdk/instance.ts
- packages/webpack-plugin/src/multiple.ts
- packages/webpack-plugin/src/plugin.ts
- packages/webpack-plugin/tests/multiple.test.ts
This MR only migrates the existing configuration without introducing any new logic. The main migration points are as follows:
- Changed mode to output.mode, while retaining the original mode configuration and logic, and adding a prompt.
- Added the output.options configuration, which is divided into NormalModeConfig and BriefModeConfig, both following the existing configuration logic.
- Removed the output.compressData configuration since no users were using it, and added a prompt.
- For mode: lite, added a prompt while retaining the original logic.
- Added tests for the new configuration items after migration.
————————————————————————————————————————————————————————
本 MR 只对原有的配置做了迁移，没有新加逻辑，迁移主要有以下几点：
- mode 改为 output.mode, 保留原先 mode 配置及逻辑，同时增加提示。
- 增加 output.options 配置分为：NormalModeConfig …
> feat: the config options changes

- .gitignore
I ran E2E tests locally and ended up with a bunch of new files ready to commit in `e2e/.rsdoctor`, let's add `.rsdoctor` to the `.gitignore`.
> chore: ignore `.rsdoctor` folder

- packages/sdk/package.json
- pnpm-lock.yaml
Declare `@types/fs-extra` as devDependency so that consumers of the library won't need to install it
> chore(deps): declare `@types/fs-extra` as devDependency

- packages/components/src/pages/Uploader/utils.ts
- pnpm-lock.yaml
fix: playground problem
The redirectUrl previously included http://, which caused a navigation to a new page. As a result, the data mounted on the window was lost, leading to an error due to missing data on the page.
> fix: playground problem

- packages/graph/src/transform/chunks/chunkTransform.ts
- pnpm-lock.yaml
fix: stats transform to assets graph
In some cases, assets will be empty, and you need to collect them from the files of chunk.
> fix: stats transform to assets graph
